### ISSUE TITLE
Complete README

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#10]
README should have important at-a-glance information for potential users, and some information for people that know what they want. A possible structure is as follows:

- Brief description for users who don't know if they are in the right place.
- Brief description for specialized users.
- Installation instructions.
- 3-5 lines example and link to documentation for further explanation.
- Directions for contributors.
- License and link to LICENSE.

**Comment by clizbe** [comment]
It looks like Diego has created a file called "how-to-use.md" with some of this information.

**Comment by datejada** [comment]
Correct! It is for the documentation; we might want to have only one file with this information, so we need to update it in one file in case of changes. Then, we just need to reference the file with the information in the markdown files. @abelsiqueira What do you think? any best practice here?

**Comment by abelsiqueira** [comment]
I suggest having a small README with the bare information (the list I have above). It should be around 50 lines at most, I imagine. In the README you link to the places with more detailed information. For instance, you can say add to the README something like

> Example:
>  ```julia
> data = read("input.esdl")
> model = create_model(data)
> solution = solve_model(model)
> ```
> 
> For more information check the [tutorial](link to tutorial page on documentation).

The snippet is short enough to be useful for people who know what they're doing. Other users can check the tutorial for more info.
