### ISSUE TITLE
Convert the current test (tiny example) into CSVs by hand

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#100]
### Summary

Use the description in #62 to change the input data of the example in the test folder into GML + CSVs files.

### Basic Example

The example is in #62

### Drawbacks

In the MOPO project it was mentioned that GML can be a challenge to work with and they're moving to GeoPackage. Maybe we can double-check it.

### Reference Issues

#62

**Comment by datejada** [comment]
Hi @abelsiqueira,

This is the first draft of the tiny example in the GML + CSV formats. Please double-check it and we can discuss it in the next working session.

BR,

Diego

[20230926-Tiny Case Study.zip](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/12729149/20230926-Tiny.Case.Study.zip)
