### ISSUE TITLE
Add parameters to the Norse case

### ISSUE THREAD

**Issue by lsoucasse** [TulipaEnergy/TulipaEnergyModel.jl#101]
For now the esdl input for the Norse case only contains the grid information (assets/ports) but no parameters (asset and not properties, profiles). Actual values do not matter but the idea is to figure out wich parameters are needed for the model.

**Comment by gnawin** [comment]
[assets.csv](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/12803182/assets.csv)
[profiles.csv](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/12803183/profiles.csv)

@datejada I created two files with dummy data, could you check and let me know if this can work? Thanks.

**Comment by gnawin** [comment]
[assets.csv](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/12803521/assets.csv)
[profiles.csv](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/12803522/profiles.csv)

Thanks for the comments. The required changes are incorporated.

**Comment by datejada** [comment]
I'll close it for now, and we can create a new issue to add this data into ESDL and translate it into Tulipa's CSV files.

**Comment by lsoucasse** [comment]
Thanks for the data. I think I can add it to ESDL.
