### ISSUE TITLE
Create `struct` to hold the Asset and Flow attributes

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#105]
Might be obsolete, check #118 first.

Create data structures (`struct`s) to hold the Asset and Flow attributes.
After #102, we should have a clearer picture to know if this is enough description for the issue.

Depends on
- #102 
- #118

**Comment by clizbe** [comment]
Blocked until Benchmark #146 #111

**Comment by datejada** [comment]
waiting on https://github.com/TulipaEnergy/TulipaEnergyModel.jl/issues/110
