### ISSUE TITLE
Create a CITATION.cff file

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#11]
For instance, using https://bit.ly/cffinit.

**Comment by datejada** [comment]
Hi @abelsiqueira! Should we first solve the repository name before creating the citation file?

**Comment by abelsiqueira** [comment]
It should be fine either way, as long as we change before the first release

**Comment by clizbe** [comment]
https://www.youtube.com/watch?v=zcgLIT5Qd4M&ab_channel=NetherlandseScienceCenter
