### ISSUE TITLE
Create a simple European case study for testing

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#112]
Create the esdl file and fill with data for the simple European case study.

**Comment by clizbe** [comment]
Zhi is coming next week (15-11)

**Comment by gzclarence** [comment]
[input_NLBE_22Nov2023.zip](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/13441389/input_NLBE_22Nov2023.zip)
@abelsiqueira @datejada 
Hi, Can you have a try on this? I had large overhead time formulating the model with Tulipa.

Thanks,
Zhi

**Comment by abelsiqueira** [comment]
@gzclarence @datejada can you update the NLBE example for the current main?

**Comment by datejada** [comment]
@gzclarence, once you have the time to create the model using version 0.5, please let us know 😄 please also post the time for the case study that includes Germany to have an idea of how the model generation scales with larger cases. Thanks!

**Comment by clizbe** [comment]
Related #426

**Comment by LauraBrafine** [comment]
[Europe_ZhiLaura.zip](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/14917115/Europe_ZhiLaura.zip)
@datejada Can you access the files like this?

Best,
Laura

**Comment by datejada** [comment]
@LauraBrafine Thanks! I downloaded it 😄
