### ISSUE TITLE
Decide whether to use DataFrames as data structures or actual structs

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#118]
Decide whether to use DataFrames as data structures or actual structs (using MetaGraphs.jl)

Maybe it is not necessary to use a separate dedicated struct to hold the data for the assets and edges since we are already reading these things from CSV files (probably into DataFrames). That means that they don't need a special structure, and therefore using the DataFrames directly should be viable.

Depends on:
- #102

**Comment by clizbe** [comment]
@abelsiqueira Can we close this one?

**Comment by abelsiqueira** [comment]
These issues are a bit related to https://jump.dev/JuMP.jl/stable/tutorials/getting_started/design_patterns_for_larger_models/ and the subsequent chapter on performance.

The question for all these issues is where we'll stand in the balance between performance and readability (code readability and log readability).

My short answer is to do what looks nicer but not obviously slow, and then benchmark/profile later.
Before we can benchmark, we need a working model from beginning to end with at least the Nordic case, and possibly the solver that we will, in fact, use.

**Comment by clizbe** [comment]
Blocked until Benchmark #111 #146

**Comment by datejada** [comment]
waiting on https://github.com/TulipaEnergy/TulipaEnergyModel.jl/issues/110
