### ISSUE TITLE
Add *.lp to .gitignore

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#120]
### Summary

Add *.lp to .gitignore

### Basic Example

```
*.lp
```

### Drawbacks

None

**Comment by datejada** [comment]
Closed in commit [40c8c08](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/commit/40c8c088e1b593edf7d9097b139eb332ba1fa2c3)
