### ISSUE TITLE
Use ids in the model formulation instead of node_name

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#125]
### Summary

The model currently uses the nodes' (assets) names as set. Instead, we should use the IDs of the nodes, since all data in the new CSV format is using the IDs.

Alternatively, we can make the IDs be node names and not the numbers.

### Basic Example

The edges are defined as `[(A[e.src], A[e.dst]) for e in edges(graph)]`, since we do a look up. Instead, we can possibly just use `edges(graph)` directly, since the `graph` is numerically indexed (and the IDs and the numerical index).

### Drawbacks

It might be harder to identify issues with specific variables and constraints. For instance, if a constraint is infeasible, we can't easily verify which variables are involved.

### Reference Issues

Should be done after #124

**Comment by clizbe** [comment]
Waiting on Benchmark #111 #146

**Comment by datejada** [comment]
waiting on #110

**Comment by clizbe** [comment]
Using the names is fine.
