### ISSUE TITLE
Change Actions to only run Ubuntu except on Main

### ISSUE THREAD

**Issue by suvayu** [TulipaEnergy/TulipaEnergyModel.jl#133]
### Summary

Actions take too long to run, and sometimes fails to run

### Basic Example

When I added a CSV I had forgotten under `test/inputs/tiny`, actions were not triggered.

### Drawbacks

The basic set of workflows for PRs should be faster, otherwise the feedback loop is quite slow.

### Reference Issues

e.g. see #132 for the CSV issue

---
**PS:** the issue templates are too restrictive

**Comment by clizbe** [comment]
What do you prefer for issue templates? I don't think we're particularly attached to the ones we made.
I agree that half the time I don't have anything for certain fields.

**Comment by suvayu** [comment]
My general annoyance is it's too restrictive for a project this early in it's lifecycle.  In the past, even for very mature projects most I have seen is:

- Ask for a summary
- How to reproduce it (if it's a bug/regression/limitation)
- What is the expected behaviour
- Followed by additional info, e.g. details of the execution environment, so platform, software version, screenshots, etc.  Generally for this, the prompt is "Run `cmd --debug --bla` and paste the output here", and place holders for other common types of info 

Usually only the summary is mandatory, and the others are prefilled, but to be edited/deleted by the issue author as needed.

So in this particular case, it would look like:

---
### Summary
The actions take too long to complete. This is particularly annoying in the case of a PR since I can't get quick feedback.

### How to reproduce
- I added a test for the input validation, but forgot to include the example CSV file.
- The tests failed, but I only realised much later because the actions took so long to run.

### Additional info
- Possible solution: I noticed the documentation builds on all runs
- Possible bug: After I added the CSV in a separate commit, the tests didn't run

**Comment by abelsiqueira** [comment]
Making the issue template less restrictive could also be done instead of #90

**Comment by abelsiqueira** [comment]
This is two issues. I will create a separate issue for the failure to run and leave here for taking too long to run. If you want to discuss the template, we can do it on #90.

**Comment by abelsiqueira** [comment]
Actually, I've opened #132, and it appears to have run the tests, so I'm not creating a new issue.

**Comment by abelsiqueira** [comment]
Two reasons the Test action take too long to run:

1. Windows on 1.6 is very slow.
Here is an example of the latest main:
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/1068752/e7705131-5313-4dc8-9f39-eaaa919f4419)

In some other cases, the difference is not so pronounced, but usually (always?) Windows is slower, and nightly builds can be slower as well. 1.6 should also be slower than 1 (which is 1.9 currently).

One short-term solution would be disabling many tests.
The most aggressive, but still useful:

- Leave only ubuntu on Julia 1 for PRs (i.e., remove all other 8 tests)
- Run normally on `main`

This would ensure faster feedback, at the cost of occasionally breaking `main` for other configurations.

2. Precompilation and compilation might be too slow

Looking at a 3 minutes run on Ubuntu + Julia 1, 2 minutes were spent on pre-compiling, and 40 seconds running the first test suite, which includes the compilation time.
We should profile to figure out why it is slow.

**Comment by clizbe** [comment]
We've decided to implement Abel's solution - with the caveat that we HAVE to wait for the actions to finish before releasing.

**Comment by datejada** [comment]
I think we need to add the test for 1.6 Julia in Ubuntu, since, for some reason, we got this in the latest commit to the main: 

<img width="260" alt="image" src="https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/12887482/b185b37f-3ac2-4270-8498-954d7bbdf942">

Any thoughts? @abelsiqueira @suvayu

**Comment by abelsiqueira** [comment]
That is exactly the drawback that I mentioned above, so it is "working/breaking" as expected :smile: . I would open a Bug issue linking to that failure since it is its own thing now.

Adding Ubuntu 1.6 won't slow the feedback loop much, but the same caveats apply: The more you test, the longer you wait, but the less frequently you break. I'm in favor of adding it, though.

**Comment by datejada** [comment]
Great! I agree, thanks :)
