### ISSUE TITLE
Include all the asset types in the formulation

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#135]
### Summary

Currently, the formulation handles producers and consumers. We need to extend it to handle conversion, storage and transmission assets (according to the ESDL description of energy assets).

In this issue, we will not include the matrix proposal for having flexible time steps.

### Basic Example

- Conversion: electrolysers, CHP, CCGTs (any that converts from one energy carrier to another)
- Storage: batteries, hydro plants
- Transmission: nodes and transmission lines

### Drawbacks

It requires more abstraction of concepts such as the balance constraint.

**Comment by clizbe** [comment]
This involves several steps so that everything works together:

- [ ] Update the documentation
- [ ] Read-in the additional data
- [ ] Update the model
- [ ] Update the tests
