### ISSUE TITLE
Use CSV and DataFrames to write the output

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#14]
Currently, it is being done manually. Instead, we should try to create a DataFrame and write to csv.

**Comment by datejada** [comment]
Hi Abel,

Do you have an example or reference on using DataFrames to save the variable results from JuMP?

Thanks!

**Comment by abelsiqueira** [comment]
> Hi Abel,
> 
> Do you have an example or reference on using DataFrames to save the variable results from JuMP?
> 
> Thanks!

Sorry, missed this comment. I don't have a direct example, checking the DataFrames and/or CSV documentation would be the way to go.
