### ISSUE TITLE
Organize tests into different files

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#152]
### Summary

Organize files into different files that correspond to their counterpart in `src` or with their function.
To avoid debugging confusion, put "test" in front of the src function name (even though this is redundant).

### Basic Example

IO tests should go in `test_io.jl`.
Basic usage can go in `test_basic.jl`.

### Drawbacks

You have to navigate the files and make sure you don't forget to add them.

**Comment by clizbe** [comment]
@abelsiqueira Does this mean every time we add a test file we have to add/call it from runtests.jl? In that case, should we add this to the README.DEV so that it's recorded somewhere?

**Comment by abelsiqueira** [comment]
We have to `include` it from `runtests.jl`. That's part of normal Julia use, so I don't think it needs to be recorded.
