### ISSUE TITLE
Describe objectives for the package

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#18]
Like a high-level TODO list, or a collection of _user stories_.

**Comment by clizbe** [comment]
When is it "done?" 
What is enough for a first release?
Maybe a roadmap?
User story should be shorter than the proposal.

**Comment by clizbe** [comment]
@datejada Should we discuss this in a meeting? Or push Germán to work more on GitHub?

**Comment by clizbe** [comment]
- File format
  Convert ESDL to GML+CSV
  (and back)
  Laurent & Wester

- Data structure
  What model consumes

- Model definition
  Sets, indices, constraints, variables

- Output comparison
  Solve time, convergence, correct solution, etc
  Basic this year, more complex next year

These are the Epics that need to be broken into smaller Issues to accomplish them.
