### ISSUE TITLE
Create function to plot

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#191]
Create a function to create graph plots and attach information to the graph.
Check https://github.com/JuliaGraphs/NetworkLayout.jl or https://github.com/JuliaGraphs/GraphPlot.jl

The following functions for plots will be added:

- [x]  time series for a single flow
- [x]  graph with flow values
- [x]  balance (stacked bar charts) for assets
- [ ]  time series for all flows?

**Comment by clizbe** [comment]
I've made the first graph and am working on the second.
I would like to scale the thickness of the connecting lines by the total capacity (initial+investment) and maybe the same for the size (or color) of the nodes - or maybe just labels.

But I can't figure out how to get this data. It means adding a Dict and a DenseAxis Array:
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/7117661a-c5a6-4692-8c0d-58e8ff6f08f4)

**Comment by clizbe** [comment]
I found a function "merge" that can add Dicts based on their keys, but it doesn't recognize a DenseAxisArray:
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/79a6c1c9-1729-4796-917a-5432a153fee9)

**Comment by abelsiqueira** [comment]
Indeed, there is no way to nicely sum these because they are different structures but also because they are not indexed on the same sets.

`parameters.flows_unit_capacity` is indexed on F and `solution.flows_investment` is indexed on Fi.

So you have to iterate on the flows and aggregate these based on what you want.

If you want all `flows_unit_capacity`, and if they are investable, add the solution, then you can do.

```julia
total = copy(parameters.flows_unit_capacity)
for f in sets.flows
    if parameters.flows_investable[f]
        total[f] += solution.flows_investment[f]
    end
end
```

And `a += b` is the same as `a = a + b`.

**Comment by clizbe** [comment]
Yes that's exactly what I need, thanks!
But also I think this is something we'll want in the output, so it might make sense to put this is post-processing, or otherwise change the structure of the data. 🤔

**Comment by clizbe** [comment]
Is there a way to ask the graph where it's connections are FROM and TO? Because now I have this data in a Dict{Tuple{String, String}, Float64} but the gplot parameter edgelinewidth is expecting just a Vector that somehow matches the order of the flows in the graph.

**Comment by datejada** [comment]
> Is there a way to ask the graph where it's connections are FROM and TO? Because now I have this data in a `Dict{Tuple{String, String}, Float64}` but the gplot parameter edgelinewidth is expecting just a Vector that somehow matches the order of the flows in the graph.

From the graph structure, something like this will give you the id and the name:

```julia
for e ∈ edges(graph)
   from_asset_id = e.src
   from_asset_name = sets.assets[e.src]
   to_asset_id = e.dst
   to_asset_name = sets.assets[e.dst]
end
```

If you are using the `F` set, then something like this should work too:

```julia
for f ∈ F
   from_asset_name = f[1]
   to_asset_name = f[2]
end
```

Depending on the information in your function, one option will be more straightforward.

@abelsiqueira, any comment, suggestion or thoughts? Thanks!

**Comment by clizbe** [comment]
With the new data format, I would like to show a directed graph with:
 - Node names with capacity values (done)
 - Export flows with capacity (normal directed graph)
 - Import flows with capacity (reverse directed graph)

I know how to calculate the export/import caps for flow A->B, but how can I get the reverse direction arrows onto the same graph to label with the import capacity? The graph just thinks there's 1 arrow that can have a positive or negative flow - but I need to show two arrows with their own capacities.

**Comment by clizbe** [comment]
I could do a non-directed graph and make the labeled capacity be a different color for export/import (or display on a different part of the line), but I think having double arrows is the better solution.

**Comment by abelsiqueira** [comment]
You will need to create a separate graph for that, since the one we have is indeed only from A to B (unless explicitly declared from B to A in the csv as well).

Here is how to construct one such graph using the existing graph:

```julia
graph
dgraph = DiGraph(nv(graph)) # Creates a graph with the same number of vertices
for e in edges(graph)
    add_edge!(dgraph, e.src, e.dst)
    add_edge!(dgraph, e.dst, e.src)
end
```

The thing is, `dgraph` is NOT a MetaGraph. So using `dgraph[u, v].some_field` will not work, so you have to get those properties from `graph`. Let me know if you need more info.
