### ISSUE TITLE
Better name for time resolution "stuff"

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#208]
### What and Why

There are representative periods, and they have time steps.
There are Assets and Flows, and they have time steps, but different time steps because of the time resolution.
There are constraints and they have time steps, but different time steps from the other two because it depends on the time resolution of the others.

In addition to possibly selecting a better naming and using it in the formulation, it will also be useful for the time-resolution file.

Example:

- RPs have time steps, where each step has a duration; Keep `num_time_steps`; Change `rp_time_scale` to `rp_time_step_duration`;
- The assets and flows are defined on the RP time steps by aggregating these into **composite intervals**. Each asset and flow has its own definition of how many intervals and how they are composed. Each `flow` is being indexed in `K[rp]`, and instead should be indexed in a new set `intervals[f, rp]`.
- The balancing constraints are defined per group of assets and flows. The intervals of these define how the time steps of the RP are aggregated. Therefore, there are **periods** for the constraints. Each constraint is defined for a set `periods[a, rp]`.

### Related Issues

- #110 will be affected

**Comment by datejada** [comment]
waiting for #110

**Comment by abelsiqueira** [comment]
@datejada, @Alfa-R, and me discussed the following:

- Each representative period (RP) has many **time steps**. (`time_step`)
- All time steps in a RP have the same duration (`time_step_duration`) - now called `time_scale`.
- A consecutive aggregate of time steps is a **time range** (`time_range`) - which is also a Julia range (e.g., `1:3`, `4:10`)
- A partition of an RP into time ranges is a **RP partition** (`rp_partition`) - in Julia, `[1:3, 4:6, ...]`.
- The following sets are defined:
  - `rp_partition_assets`
  - `rp_partition_flows`
  - `rp_partition_constraints` - defined by the assets and flows above.

**Comment by abelsiqueira** [comment]
@g-moralesespana, could you check this out and approve, please?

**Comment by g-moralesespana** [comment]
I think it is a bit confusing because all this is new, which is fine but we should illustrate all these definitions with examples.

**Comment by Alfa-R** [comment]
there is also `rep_weight` that I will rename to `rp_weight`

**Comment by Alfa-R** [comment]
also there was a dictionary of time steps per representative period called `time_steps`. Renamed to `rp_time_steps` to indicate the connection to representative periods
