### ISSUE TITLE
Function to run_scenario

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#209]
### Description

Is it just me or do we need a wrapper* function that runs a given scenario automatically?
That way we can just call one function and it reads the inputs, runs the model, and saves the outputs.
We have all the steps listed several times in the test-case-studies file, but I don't see a basic function anywhere.

This would also enable simply using Tulipa from Julia, without coding a bunch of lines.

Example:
*This function looks for a folder with the given name (or takes a specific folder) and runs the model, then prints the output.*
`run_scenario(Norse)`
`run_scenario(input_folder)`

*I don't know if this is the correct usage of "wrapper"

**Comment by abelsiqueira** [comment]
I second the idea, and wrapper is a good description
