### ISSUE TITLE
Add an input column for assets and investments to select MIP or LP investments

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#214]
### What and Why

We need to add a new boolean type of column in the input data with the parameter `is_investment_mip`, values `{true, false}` to indicate if the investment variable of the asset/flow is defined as `Int` in JuMP or as linear.

Then, in the model, the variable should be defined accordingly to consider it in the model as linear or integer.

### Possible Drawbacks

More input data 🤷 
We can in a later stage from the UI simplify the input data writing for the user.

**Comment by datejada** [comment]
waiting on https://github.com/TulipaEnergy/TulipaEnergyModel.jl/issues/110

**Comment by clizbe** [comment]
This should be in the scenario specification and not in the raw input data.
