### ISSUE TITLE
Create a new tiny test using different time resolutions

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#225]
### Description

Something like (A1 -> A2 -> A3), where (A1, A2) has 4-hour res. and (A2, A3) has 3-hour res.

**Comment by clizbe** [comment]
@abelsiqueira Would this be in one of the -partitions files or in the rep-periods-data?

**Comment by clizbe** [comment]
And by A1, A2, A3 do you mean Assets or something else?

**Comment by abelsiqueira** [comment]
The `-partitions` file.

A1, A2, and A3 are assets.

**Comment by clizbe** [comment]
Thanks - I'm still a bit confused about all the time-stuff, so Diego's gonna help me with it. :)

**Comment by clizbe** [comment]
@datejada Please help make this a useful test with a verifiable solution. :)

**Comment by clizbe** [comment]
Unassigning myself unless @datejada needs my help.
