### ISSUE TITLE
Produce feedback for failed benchmark runs

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#234]
### What and Why

When the `/run-benchmark` command fails, we don't get a notification. It would be useful to have a comment to warn of the failure.

**Comment by datejada** [comment]
@abelsiqueira, I have a quick question: Is the improvement in #395 solving this problem?

**Comment by abelsiqueira** [comment]
Not exactly, but I would say yes.
The new system creates an action like the ones we normally use, so failures will be visible. But we haven't actually tested it yet, so it might be better to wait a bit before closing.
