### ISSUE TITLE
Include solver & options in call to optimize

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#246]
### What and Why
Be able to specify solver and set certain aspects of solver with a file or in the function to solve the model.

For example, change absolute and relative gap of Highs:
Make tests hit absolute and relative 0 so they always have exact same answer.
Should be options in our solve function (or somewhere).

**Comment by abelsiqueira** [comment]
Ref.: https://jump.dev/JuMP.jl/stable/manual/models/#solver_options

**Comment by abelsiqueira** [comment]
@suvayu

**Comment by gnawin** [comment]
Currently, the solver name (i.e., HiGHS) and one solver option ("output_flag") is given in the function `create_model!`. It makes more sense to specify all theses outside this function, so the model can be independent of the used solver and its options. 

Possible places are either `solve_model`, or a separate file that is an argument for this function.
