### ISSUE TITLE
Add linked-representative days formulation for seasonal (long-term) storage

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#255]
### What and Why

This is one of the core features of the model. It is based on the following formulation:

https://ieeexplore.ieee.org/abstract/document/8334256

We need to translate this to the current formulation of Tulipa.

### Possible Drawbacks

We need more input data and possibly a new file.

Also, @abelsiqueira, I need your help to tackle these changes (maybe we can use the same logic of ranges to simply the proposed formulation in the paper)

### Related Issues

- [x] #455 
- [x] #456
- [x] #509
- [x] #512
- [x] #516
- [x] #522
- [x] #523
- [x] #514
- [x] #549
- [x] #458 
- [x] TulipaEnergy/TulipaPlots.jl/issues/15

**Comment by datejada** [comment]
Blocked by #336

**Comment by datejada** [comment]
For implementation, we should do the following:
- Define new subsets for the short- and long-term storage (subsets of storage assets)
- A set for the inter-day storage window period (e.g., `w`)
- New variable `storage_level_interday(storage asset,w)` (double check if we want this only for long-term storage or both)
- Use the rp_mapping_df to get the `mapping` of the periods to `rp` and compute the weights per window `w`
- To construct the inter-window (period) constraint, you can use it as a matrix multiplication where the `mapping * delta_charge` is used. Double-check if it is possible because the `w=0` you want a constant.

**Comment by abelsiqueira** [comment]
I think you meant `inter` in the third bullet point.

**Comment by datejada** [comment]
I added issue #507 to explore the option of having the same idea of partitions in the inter-period constraints. I don't count the issue into this Epic issue because the milestone doesn't depend on whether we implement this. So, at the moment of its creation, it is an `Eventually` label.

**Comment by datejada** [comment]
All issues have been completed! 🥳
