### ISSUE TITLE
Update formulation in the documentation with the ranges/matrices 

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#256]
### What and Why

The current mathematical formulation in the documentation is according to temporal handling in the model.

### Possible Drawbacks

The main drawback is that it will be more challenging to follow the mathematical formulation of Tulipa. Therefore, we should have a formulation in the documentation that is the simplest possible. In other words, we keep the formulation in the documentation as a `vanilla version` to keep it readable and simple and add sections for the temporal structure and other more complex topics that require a certain level of abstraction.

@g-moralesespana, @abelsiqueira, and @clizbe What do you think?

**Comment by clizbe** [comment]
Idea is to have the vanilla doc for the formulation and another section for temporal structure explanation and examples.
