### ISSUE TITLE
Check if Lazy Loading is possible

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#28]
Lazy Loading is loading only the data needed for the current run, not ALL data.
This method is for saving RAM.

**Comment by abelsiqueira** [comment]
This was discussed as a feature that GAMS and/or AIMMS had. Can we have a reference for that?

cc. @g-moralesespana

**Comment by g-moralesespana** [comment]
AIMMS has an example I could not find, but check page 16 of [this AIMMS document](https://download.aimms.com/aimms/download/manuals/AIMMS3TP_FunctionsAndProcedures.pdf)
"...Note that the weekly demand is read for only those weeks that are in the cur
rent planning interval..."
The databases will be huge, we should only load the information needed to solve the current optimization problem.

**Comment by abelsiqueira** [comment]
This seems like a problem of the data loading part only, so I guess it will be related to #289. And I think nothing needs to be done from the JuMP side, which is good.

**Comment by datejada** [comment]
Since there are no foreseeing actions for this issue, we close it and check if an action appears in #289 on this topic again.
