### ISSUE TITLE
Add "run on save" of Julia Formatter to README.dev

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#29]
In VSCode (or similar) you can change your settings so that the Julia Formatter runs when you save. We should tell people to enable this in the README.dev.
This makes sure your code works in the Julia Formatter before running pre-commit, etc.

**Comment by clizbe** [comment]
@abelsiqueira  How to do this? I tried changing the key command for "Format Document" to CTRL+S, but it doesn't seem to work.

**Comment by abelsiqueira** [comment]
Open the VSCode Setting (CTRL+,), in the "Search settings" input, write "Format on Save", and tick the first result.
Should look like this:
![image](https://github.com/TNO-Tulipa/TulipaBulb.jl/assets/1068752/23cc4f95-48d3-417b-a051-72f692535142)
