### ISSUE TITLE
Allow non-EnergyModel usage

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#293]
We should allow an user to run TulipaEnergyModel without having to create or use an EnergyProblem structure.
This issue has been created after a discussion on whether having the structure is beneficial or not.

**Comment by clizbe** [comment]
This is cryptic to me...

**Comment by clizbe** [comment]
But if it's an optional thing, is it such a high priority? Seems like something we could add later, if our default is to make the structure.

**Comment by abelsiqueira** [comment]
I think the objective is to see which is better while we use it. It is not a lot of work, and it should be done in #299, it just needs some finishing touches. I am mostly in meetings and other projects today, but I think I will have it done by EOD.
