### ISSUE TITLE
Profile the problem solving

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#294]
The simplified european model by @gzclarence takes 5 minutes to build and solve. We need to profile it.

Some references:
https://www.youtube.com/watch?v=BFvpwC8hEWQ&ab_channel=TheJuliaProgrammingLanguage
https://www.youtube.com/watch?v=Okn_HKihWn8&ab_channel=TheJuliaProgrammingLanguage
https://docs.julialang.org/en/v1/manual/profile/

**Comment by abelsiqueira** [comment]
@gzclarence

**Comment by gzclarence** [comment]
> The simplified european model by @gzclarence takes 5 minutes to build and solve. We need to profile it.
> 
> Some references: https://www.youtube.com/watch?v=BFvpwC8hEWQ&ab_channel=TheJuliaProgrammingLanguage https://www.youtube.com/watch?v=Okn_HKihWn8&ab_channel=TheJuliaProgrammingLanguage https://docs.julialang.org/en/v1/manual/profile/

Thanks a lot for the information!

**Comment by clizbe** [comment]
@abelsiqueira I don't know if I can wait till tomorrow to find out... How's it going? 😶

**Comment by abelsiqueira** [comment]
There were various improvements (#315, #317, #319). The benchmark script is maybe not working, so I am benchmarking locally. The NLBE example from @gzclarence is not up-to-date with the current CSV requirements, so I haven't tested on it yet.

**Comment by abelsiqueira** [comment]
This has been done up to a reasonable point. With the changes since ~1-2 weeks ago, we have:

Old version:
- Create graph and RPs: ~50s
- Create constraints partitions: ~40x
- Create model: ~500s

New version:
- Create graph and RPs: < 1s
- Create constraints partitinos: ~3.5s
- Create model: ~35s

I don't know if we want to close this and open a new one to continue improving the model, or just change the priority.

**Comment by abelsiqueira** [comment]
With #407 and #408, we have the model creation down to 3-5 seconds. The dataframes version is more complicated but is faster. After #112 we can verify again how they scale, but I am guessing that the dataframes version will be better.
