### ISSUE TITLE
The variable cost of flow does not get multiplied by the partition range

### ISSUE THREAD

**Issue by gzclarence** [TulipaEnergy/TulipaEnergyModel.jl#300]
### Description

Hi all,

I have built the case NL & BE. When I implement the uniform partition 2 on all BE-related assets and flows, I get 2/3 of the objective value, compared with when I have both in uniform partition 1.

I think this is because, in the objective, the variable cost of the flow does not get multiplied by the timesteps it covers. So when we have 1/2 of the flow variables in one of the two countries, we get 2/3 of the objective value. 

Is there any way to fix this? I would like to have an objective that is constant with time partition (counting every time step regardless of the partition).

[input_NLBE_1h2h_27Nov2023.zip](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/13480699/input_NLBE_1h2h_27Nov2023.zip)
[input_NLBE_27Nov2023.zip](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/13480700/input_NLBE_27Nov2023.zip)

### Reproduction steps

```bash
1. Run both cases "input_NLBE" and "input_NLBE_1h2h".
2. Notice that the objective value differs significantly, which should not happen.
```

### Logs

```bash
flows_variable_cost = @expression(
        model,
        sum(
            representative_periods[rp].weight *
            graph[u, v].variable_cost *
            flow[(u, v), rp, B_flow] for (u, v) ∈ F, rp ∈ RP,
            B_flow ∈ graph[u, v].partitions[rp]
        )
    )

Can we multiply here with the length of B_flow?
```

**Comment by gzclarence** [comment]
I fixed this by changing the variable cost into:

    flows_variable_cost = @expression(
        model,
        sum(
            representative_periods[rp].weight *
            graph[u, v].variable_cost *
            flow[(u, v), rp, B_flow] * length(B_flow) for (u, v) ∈ F, rp ∈ RP,
            B_flow ∈ graph[u, v].partitions[rp]
        )
    )

Can anyone tell me whether calling length() here is an efficient way?

**Comment by datejada** [comment]
@gzclarence, thanks for posting the bug and solving it 😄 Your proposed solution works, and I'm not aware of a better function to get the duration. @abelsiqueira, any other suggestions?

**Comment by abelsiqueira** [comment]
The representative period also has a resolution, to you have to multiply by that as well. Using `length` is correct. It is the simplest way to compute the number of time steps in `B_flow`. Here is the `duration` used in the model for the intersection of time blocks:

https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/9e2dd716d93c9e324101e6ea96f7e55d1b336d36/src/model.jl#L89-L91

**Comment by datejada** [comment]
@gzclarence the fix is already in the main branch, you can update the code to get the latest version. If you find more weird results, please don't hesitate to create a new issue 😄
