### ISSUE TITLE
Test @expression vs Dict for the calculation of flow_max_capacity

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#305]
### What and Why

The current calculation of the `flow_max_capacity` uses the `expression` macro in JuMP. There is a question from @abelsiqueira if it might be faster to use a Dict instead. So, this issue is to test both ways and change (or not) the code.

**Using expression in JuMP**
```julia
    @expression(
        model,
        flow_max_capacity[(u, v) ∈ Fi],
        max(graph[u, v].export_capacity, graph[u, v].import_capacity)
    )
```

**Using Dictionary**
```julia
flow_max_capacity = Dict((u, v) => max(graph[u, v].export_capacity, graph[u, v].import_capacity) for (u, v) in Fi)
```

### Possible Drawbacks

N/A

**Comment by clizbe** [comment]
Might be irrelevant - please check @datejada
