### ISSUE TITLE
Create a log file recording the time spent for every step of the workflow

### ISSUE THREAD

**Issue by gnawin** [TulipaEnergy/TulipaEnergyModel.jl#308]
### Description

Currently there is no information about the time spent for the workflow.

This should concern every step, e.g., reading the data, creating the model, running the model etc.
The time information can be start time, end time, and duration.

Also adding an option of whether printing the above info, and/or write to a log file for future inspections.

**Comment by abelsiqueira** [comment]
Maybe something like this: https://github.com/KristofferC/TimerOutputs.jl
For instance, we can use it inside the `run_scenario` function.
