### ISSUE TITLE
The `overall_output_flows` constraint should be written in the highest resolution not the lowest

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#313]
### What and Why

The overall output constraint is to limit the capacity (i.e., power), so it should be in the highest resolution. We need to double-check if, after this change, we need the upper bound constraints since they might not be necessary anymore (analyze the case with investment).
**Generally, all energy-related constraints (e.g., balance) should be in the lowest resolution, whereas all capacity-related constraints should be in the highest resolution.**
We need to update the documentation too.

### Possible Drawbacks

N.A.

**Comment by abelsiqueira** [comment]
Yes, after 9h, please. Send me an invite.
