### ISSUE TITLE
Implement show for the EnergyProblem type

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#321]
### What and Why

We can make the display of an EnergyProblem variable look nicer following https://docs.julialang.org/en/v1/manual/types/#man-custom-pretty-printing

**Comment by abelsiqueira** [comment]
I set the Zone as documentation, but it could be closer to UI or UX.

**Comment by clizbe** [comment]
Or output!
