### ISSUE TITLE
Add prices to the solution of the model

### ISSUE THREAD

**Issue by gnawin** [TulipaEnergy/TulipaEnergyModel.jl#328]
### What and Why

Currently the solution object consists of results that are directly the values of the variables, we also need to add prices (i.e., the dual variables of the hub assets).

**Comment by datejada** [comment]
We need to take into account the type of model and solver we use:

- For LP problems, both open-source and commercial solvers return the dual variables from the optimal solution
- For MIP problems, commercial solvers return the duals from the final integer solution by fixing the integer variables and solving an LP problem (it is one way to do it). However, this procedure is not done in an open-source solver (e.g., HiGHS), which normally does not return dual variables for MIP problems.

We can keep it simple and don't do any fancy stuff, and just retrieve the duals always and include a note in the documentation explaining what is happening if you use an open-source solver to solve a MIP problem.

**Comment by gnawin** [comment]
If we have to test it on Github using an open-source solver, as you mentioned, then most probably we'd have to do some fancy stuff (as you suggested, and maybe there are other ways we can discuss). But I'm not sure if it is okay/possible to only test it locally?

**Comment by datejada** [comment]
@abelsiqueira proposal is how Gurobi/Xpress/CPLEX do it. So, I like the idea of having that internally implemented when we don't get dual information from the open-solvers.

One last remark about HiGHS; it doesn't fail when you ask the duals in an MIP run. It returns zeros. So, you can ask for the dual, but the value is zero 😝

**Comment by datejada** [comment]
In this section of the documentation, they show how to use the function [fix_discrete_variables](https://jump.dev/JuMP.jl/dev/api/JuMP/#JuMP.fix_discrete_variables) to fix all the discrete variables and get the duals in a MIP:

https://jump.dev/JuMP.jl/dev/tutorials/linear/mip_duality/

Basically, we need to check first if there are duals (in the case of CPLEX, GUROBI, and XPRESS, they provide them for MIPs); if not (e.g., HIGHS, CBC), then you use this function to fix and solve again. See the reply here:

https://discourse.julialang.org/t/highs-duals-for-mips/88817/2

This trick will do for what we want 😄

**Comment by gnawin** [comment]
@datejada Nice! I can start working on this this Wednesday if there are no other pressing issues.

**Comment by clizbe** [comment]
Also include option to rerun model with fixed integer variables to produce duals. #353
