### ISSUE TITLE
Merge two `run_scenario` functions into one

### ISSUE THREAD

**Issue by gnawin** [TulipaEnergy/TulipaEnergyModel.jl#343]
### What and Why

There are two `run_scenario` functions in `run-scenario.jl`. Maybe it is a better idea to use one function.

This following should work

```
function run_scenario(
    input_folder::AbstractString,
    output_folder::String = "";
    write_lp_file = false,
)
    energy_problem = create_energy_problem_from_csv_folder(input_folder)
    create_model!(energy_problem; write_lp_file = write_lp_file)
    solve_model!(energy_problem)

    output_folder == "" ? nothing : save_solution_to_file(output_folder, energy_problem)

    return energy_problem
end
```

What do you think? @clizbe

**Comment by clizbe** [comment]
Yeah I agree this would work.
@abelsiqueira What do you think? The idea is that the function works with or without the output folder, and if it's specified it writes the output.
