### ISSUE TITLE
Change the `compute_rp_partition` function strategies

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#344]
### What and Why

Currently, we have two strategies in the `compute_rp_partition`: `:greedy, :all`

We use the `:greedy` strategy to determine the lowest resolution for the balance constraints, whereas the `:all` strategy determines capacity constraint limits.

The `:all` strategy considers the outgoing and incoming flows to determine the highest resolution. This creates redundant constraints in the maximum outflow/inflow capacity limit. So, we need strategies for each one individually to have the highest resolution for the output flows and the highest resolution for the input flows separately.

We are not going to use the current `:all` strategy for the time being. Maybe we will use it in the future, I'm not sure. @g-moralesespana what do you think? any extra thoughts on this issue?

### Possible Drawbacks

More pre-computed partitions can lead to higher building model times (or maybe not...since there are more partitions to calculate but much simpler to determine)

### Related Issues

#355

**Comment by abelsiqueira** [comment]
We can use the `:all` strategy but limit the input to only the input, I think. Same for output. Would that work?

**Comment by abelsiqueira** [comment]
I.e., we don't need a separate strategy, just a separate call.

**Comment by datejada** [comment]
@abelsiqueira, that sounds even better 😄

**Comment by clizbe** [comment]
@datejada Please check if this issue is still valid or if it's already implemented.

**Comment by datejada** [comment]
We need to consider the following types of constraints:

| name | variables involved | Parameters involved | Constraint type | Resolution of the constraints | Parameter aggregation |
|--|--|--|--|--|--|
|`consumer_balance`| inputs, outputs | demand | power | min(inputs,outputs) | average |
|`storage_balance` | inputs, outputs, storage level | inflows | energy | max(asset, min(inputs,outputs)) | sum |
|`hub_balance` | inputs, outputs | - | power | min(inputs,outputs) | - |
|`conversion_balance` | inputs, outputs | - | energy | max(inputs,outputs) | - |
|`max_output_flows_limit` for `Ap` | outputs | production | power | min(outputs) | average |
|`max_output_flows_limit` for `As` | outputs | - | power | min(outputs) | - |
|`max_output_flows_limit` **or** `max_input_flows_limit` for `Acv` | outputs **or** inputs | - | power | we need to choose to apply either the outputs or inputs and the resolution is the min(outputs) **or** min(outputs) | - |
|`max_input_flows_limit` for `As` | inputs | - | power | min(inputs) | - |
|`max_transport_flow_limit` | flow | capacity | power | if it connects two hubs or demands then max(hub_a,hub_b) otherwise its own? | average |
|`min_transport_flow_limit` | flow | capacity | power | if it connects two hubs or demands then max(hub_a,hub_b) otherwise its own? | average |

Some definitions:
- power: in the highest resolution
- energy: in the lowest resolution (multiplied by durations)

This implies that we should add more strategies to create the partitions, currently we only have two (`:greedy`, `:all`). In both strategies, we consider all the resolutions related to the asset (the asset itself, the inputs, and the outputs). From this table we can foresee more cases:

- highest resolution for only the outputs (`max_output_flows_limit`)
- highest resolution for only the inputs (`max_input_flows_limit`)
- highest resolution between inputs and outputs (`consumer_balance` and `hub_balance`)
- lowest resolution between inputs and outputs (`conversion_balance`)
- lowest resolution between the asset and the inflows/outflows (`storage_balance` -> `max(asset, min(inputs,outputs))`)

Please double-check this summary @g-moralesespana @greg-neustroev @gnawin, especially the **last two rows** in the table, since I'm unsure if they need a special strategy or are covered by the list above.

@abelsiqueira, we might need to discuss these changes before implementing them in the code.

**Comment by abelsiqueira** [comment]
@datejada, on the Norse data, for asset "Midgard_Hydro", there are no incoming flows. Is that allowed/correct?
In that case then `max_input_flows_limit` simply does not exist?

**Comment by datejada** [comment]
@abelsiqueira, That's allowed. We should also consider cases where hydro storage assets don't have incoming flows. The Norse case is great because it covers all the asset configurations we want to include in the model 😄. This way, we won't forget to account for these cases when updating the model. Although the objective function isn't stable yet, hopefully, it will be soon.
