### ISSUE TITLE
Transport assets export/import capacity refactor

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#345]
### What and Why

The current parameter names for the transmission assets are:

Name|Domain|Description|Units
 ---|---|---|---
$p^{init\_capacity}_{f}$       | $\mathcal{F}$      | Initial capacity of flow connections    | [MW]
$p^{export\_capacity}_{f}$     | $\mathcal{F}_t$    | Export capacity of flow connections     | [MW]
$p^{import\_capacity}_{f}$     | $\mathcal{F}_t$    | Import capacity of flow connections     | [MW]

The constraints use these parameters for the flow capacity and the investment potential:

*Max flow capacity*

```math
\begin{aligned}
v^{flow}_{f,rp,k} \leq p^{profile}_{f,rp,k} \cdot \left(p^{init\_capacity}_{f} + p^{export\_capacity}_f \cdot v^{investment}_f \right)  \quad
\\ \\ \forall f \in \mathcal{F}_t, \forall rp \in \mathcal{RP},\forall k \in \mathcal{K}
\end{aligned}
```

*Min flow capacity*
```math
\begin{aligned}
v^{flow}_{f,rp,k} \geq - p^{profile}_{f,rp,k} \cdot \left(p^{init\_capacity}_{f} + p^{import\_capacity}_f \cdot v^{investment}_f \right)  \quad
\\ \\ \forall f \in \mathcal{F}_t, \forall rp \in \mathcal{RP},\forall k \in \mathcal{K}
\end{aligned}
```

*Investment potential*

```math
v^{investment}_f \leq \frac{p^{investment\_limit}_f}{\max\{p^{export\_capacity}_f,p^{import\_capacity}_f\}} \quad
\\ \\ \forall f \in \mathcal{F}_i
```

The drawbacks of this approach are:

1. The import/export capacities only multiply the investments. So, if you have a problem with no investments, the export/import capacity equals the $p^{init\_capacity}_{f}$  in both directions. We would also like to have different initial capacities in both directions.
2. For the potential, you need to calculate the maximum value of export and import capacities since there is no unified increment for transport assets.

There are two initial options to overcome these drawbacks:

**OPTION 1**
Split the initial capacity parameter into two parameters, one for the exports and the other for the imports:

Name|Domain|Description|Units
 ---|---|---|---
$p^{init\_export\_capacity}_{f}$       | $\mathcal{F}$      | Initial export capacity of flow connections    | [MW]
$p^{init\_import\_capacity}_{f}$       | $\mathcal{F}$      | Initial import capacity of flow connections    | [MW]
$p^{export\_capacity}_{f}$     | $\mathcal{F}_t$    | Export capacity of flow connections     | [MW]
$p^{import\_capacity}_{f}$     | $\mathcal{F}_t$    | Import capacity of flow connections     | [MW]

The constraints use these parameters for the flow capacity and the investment potential:

*Max flow capacity*

```math
\begin{aligned}
v^{flow}_{f,rp,k} \leq p^{profile}_{f,rp,k} \cdot \left(p^{init\_export\_capacity}_{f} + p^{export\_capacity}_f \cdot v^{investment}_f \right)  \quad
\\ \\ \forall f \in \mathcal{F}_t, \forall rp \in \mathcal{RP},\forall k \in \mathcal{K}
\end{aligned}
```

*Min flow capacity*
```math
\begin{aligned}
v^{flow}_{f,rp,k} \geq - p^{profile}_{f,rp,k} \cdot \left(p^{init\_import\_capacity}_{f} + p^{import\_capacity}_f \cdot v^{investment}_f \right)  \quad
\\ \\ \forall f \in \mathcal{F}_t, \forall rp \in \mathcal{RP},\forall k \in \mathcal{K}
\end{aligned}
```

PRO: we solve the drawback 1
CONS: we still have the drawback 2 (and more parameters)

**OPTION 2**
Split the initial capacity parameter into two parameters, one for the exports and the other for the imports. Moreover, there is only one parameter for the investment increments on the transport asset.

Name|Domain|Description|Units
 ---|---|---|---
$p^{init\_export\_capacity}_{f}$       | $\mathcal{F}$      | Initial export capacity of flow connections    | [MW]
$p^{init\_import\_capacity}_{f}$       | $\mathcal{F}$      | Initial import capacity of flow connections    | [MW]
$p^{unit\_capacity}_{f}$       | $\mathcal{F}$      | Capacity increment for flow connections investment  (both exports and imports)          | [MW]

The constraints use these parameters for the flow capacity and the investment potential:

*Max flow capacity*

```math
\begin{aligned}
v^{flow}_{f,rp,k} \leq p^{profile}_{f,rp,k} \cdot \left(p^{init\_export\_capacity}_{f} + p^{unit\_capacity}_f \cdot v^{investment}_f \right)  \quad
\\ \\ \forall f \in \mathcal{F}_t, \forall rp \in \mathcal{RP},\forall k \in \mathcal{K}
\end{aligned}
```

*Min flow capacity*
```math
\begin{aligned}
v^{flow}_{f,rp,k} \geq - p^{profile}_{f,rp,k} \cdot \left(p^{init\_import\_capacity}_{f} + p^{unit\_capacity}_f \cdot v^{investment}_f \right)  \quad
\\ \\ \forall f \in \mathcal{F}_t, \forall rp \in \mathcal{RP},\forall k \in \mathcal{K}
\end{aligned}
```

*Investment potential*

```math
v^{investment}_f \leq \frac{p^{investment\_limit}_f}{p^{unit\_capacity}_f} \quad
\\ \\ \forall f \in \mathcal{F}_i
```

PRO: we solve the drawbacks 1 and 2
CONS: the increments are the same size in both directions (exports/imports)

I'm open to more options here 😄 

### Possible Drawbacks

We should choose the option that is clearer for the user when including input data.

**Comment by clizbe** [comment]
After discussion, we chose Option 2.
