### ISSUE TITLE
Compare output to expected output

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#35]
Compare output to expected output, i.e., test that the output of the solver is correct.

**Comment by clizbe** [comment]
I think this can be done with just a dataframe comparison of:
D1==D2
And checking the output.

**Comment by datejada** [comment]
@clizbe I agree; the current test with the different test cases (Tiny, Tiny with variable resolution, and Norse) are more than enough. We can close this issue.
