### ISSUE TITLE
Obsolete function `resolution_matrix`

### ISSUE THREAD

**Issue by gnawin** [TulipaEnergy/TulipaEnergyModel.jl#351]
### What and Why

The function `resolution_matrix` is obsolete. It also appears in the documentation and the tests.

I propose to remove it.

Quote from @abelsiqueira 
"I am not sure because who knows what will be required to achieve the speed up required for the project.
That being said, with proper commit naming, it should be easy to find it back if we remove it, so it is fine to remove it, in my opinion"

**Comment by clizbe** [comment]
Go for it!
