### ISSUE TITLE
Compare using NamedTuples instead of Dict for the parameters

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#36]
Dicts are

```julia
D = Dict(:a => 1, :b => 2)
```

and NamedTuples are

```julia
N = (a = 1, b = 2)
```

You can access named tuples via `.`, like `N.a`.

NamedTuples are like structures without name. They don't use strings and they are immutable, so they might be more efficient.

Also, it makes more sense, since they are parameters that won't be changed within the code.

**Comment by clizbe** [comment]
Blocked by Benchmarking #111 #146

**Comment by clizbe** [comment]
Blocked by #237

**Comment by abelsiqueira** [comment]
Probably obsolete after #263
