### ISSUE TITLE
[BUG] Fix CompatHelper action

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#39]
It runs daily and it is failing. I did something similar here: https://github.com/abelsiqueira/ProbabilityThing.jl/pull/1 and possibly something has to be enabled in the settings. Haven't checked yet.

**Comment by abelsiqueira** [comment]
Unassigning myself until #40 is done.

**Comment by abelsiqueira** [comment]
This was not done. It needs permissions to create pull requests. Someone needs to enable write permissions and check the box to allow PRs from actions in https://github.com/TulipaEnergy/TulipaEnergyModel.jl/settings/actions
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/1068752/b26c2a26-bd55-472b-be59-1654b7bd7879)

@datejada, can you do that?

**Comment by abelsiqueira** [comment]
Now really done.

**Comment by clizbe** [comment]
I get notifications daily that this is still an issue :(
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/f1a369d0-19d1-4536-8738-a50c8f197c0f)

**Comment by abelsiqueira** [comment]
It looks like these issues happen on your fork, @clizbe. Can you confirm that the same settings have been fixed on your fork?
