### ISSUE TITLE
Add references to docstrings & documentation

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#397]
### Discussed in https://github.com/TulipaEnergy/TulipaEnergyModel.jl/discussions/81

<div type='discussions-op-text'>

<sup>Originally posted by **clizbe** September 18, 2023</sup>
An article reviewing energy models compared how many papers were cited in the model - it would be nice if we reference all of ours.
This falls under the clarity of documentation as well.

Probably as simple as a hyperlink, but I don't know.</div>

**Comment by clizbe** [comment]
Setting priority as Soon because it's nice to just have it and do it as we go.

**Comment by clizbe** [comment]
Waiting for some papers to be published.

**Comment by datejada** [comment]
The **References** section has been added to the documentation in the Mathematical Formulation on PR #565. The references will be updated as we publish the papers or add features based on publications.
