### ISSUE TITLE
[BUG] Benchmark action is still not working or broken again

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#403]
### Description

I forgot that we can't have ~nice things~ use of the secrets because we fork, so we need to use the old workaround of using comments.

### Reproduction steps

```bash
Check the benchmark action
```

**Comment by abelsiqueira** [comment]
@datejada @clizbe @suvayu 

The new benchmark package (AirspeedVelocity.jl) has some decisions that make it harder to run reliably across forks.
Furthermore, we already had the limitation that forks can't use the main repo secrets, so they can't post the benchmarks in the PR.
It should be possible to hack a solution for both things (the second one is almost done), but I am not sure that the increased burden is worth it if we don't have to benchmark frequently, given a simple solution would be to branch from within the main repo instead of forking.

So I propose that we do the following: When we want to benchmark something, we use the main-repo-branching-no-fork procedure, otherwise, we keep doing what we're already doing.
All the "tooling" for this is already in place.

Drawbacks:
- We might have to occasionally close an existing PR to open a new one from within when we decide to benchmark something.
- We have to remember to delete the branches after they are merged (which is just another button press in the PR screen).

Assumptions:
- We don't want to benchmark frequently.
- We don't want to change our forking workflow.
- We don't want to add too much custom scripting in the workflows to keep the maintainability burden in check.
---

More details for problem 1: The AirspeedVelocity package uses the URL and different revisions to compare. Since we want to compare `TulipaEnergy/main` and `fork/branch`, this is not possible. So we have to ensure that `fork/main` is up-to-date online. The solution would be adding some intermediary steps in the build process to check for that, or to try to bypass that.

**Comment by datejada** [comment]
@abelsiqueira I think your proposal is a fair compromise between running the benchmark and not overcomplicating it. For me, as long as this procedure is straightforward in the READMEdev.md, it is OK to go like this.

**Comment by clizbe** [comment]
I agree. We don't benchmark that often, so a convoluted automatic solution is worse than a straightforward tedious one.
