### ISSUE TITLE
The western EU case results in an infeasible optimization problem 

### ISSUE THREAD

**Issue by gzclarence** [TulipaEnergy/TulipaEnergyModel.jl#419]
### Description

I am trying to get some results from the western EU case. However, I see that the optimization problem is infeasible, reported by the solver. I do not have an idea why yet. I am working on this. More progress will follow later under this issue.

In the meanwhile, if you have found anything about this, please let me know!

### Reproduction steps

```bash
1. Go to 'Benchmark/EU'
2. Make a model and solve it.
3. The solver reports it as an infeasible optimization problem.
```

**Comment by datejada** [comment]
Hi, @gzclarence. Is there any news on the infeasibility? Were you able to do the IIS procedures (either the one in JuMP or the Gurobi one)?
Let us know if you need help on this

**Comment by gzclarence** [comment]
Hi Diego,

Thanks for asking! Last week, I have solved the infeasibility. And I have
run the planned optimization runs (WEU all 1hour and 1h2h3h based on
neighborhoods). Now I am checking the results.

This week my schedule is less hectic than last week. So I can try to make a
pull request for updating the latest dataset. How is it going with the
superfast Tulipa version? :D

Kind regards.
Zhi

Diego Alejandro Tejada Arango ***@***.***>于2024年1月26日
周五14:46写道：

**Comment by datejada** [comment]
Hi @gzclarence great news. In the next meeting, it would be nice if you could explain in more detail how you solve the infeasibility to see if we can do something from the modelling side to avoid it in the future. Next Tulipa meeting will be on Monday (5th of February)

Regarding the superfast Tulipa version, the results are promising. We are planning to merge it tomorrow. So, if you send a PR with the new data you have today that will be great. No worries about the results, we are testing memory usage and speed to build the model. We are interested in both all 1h and 1h2h3h.

Thanks!

Diego

**Comment by datejada** [comment]
The infeasibility was due to an error in the input data, not the model.
