### ISSUE TITLE
[BUG] - The codecov badge in the README.md status is unknown 

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#422]
### Description

<img width="631" alt="image" src="https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/12887482/cd721613-27fc-45f0-ab55-2b953d948ead">

### Reproduction steps

```bash
Please take a look at the screenshot in the description.
```

**Comment by abelsiqueira** [comment]
The solution in #423 indeed worked.
