### ISSUE TITLE
Make plots dependencies optional

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#424]
The plots dependencies are too heavy. It could be beneficial to only load them if the user requires plotting.
Julia 1.9 allows defining [package extensions](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)). This means that the plot code would only be loaded if the user adds Makie explicitly.
There is a workaround for Julia before 1.9 that would work in the same way, but would add another dependency called Requires.
This increases the complexity of the package, so maybe it is not the best solution.

One alternative is to create a separate package, e.g. TulipaPlots.jl. This increases maintenance complexity, not code complexity.
I don't have a strong opinion either way, because I haven't tried package extensions yet.

**Comment by clizbe** [comment]
@suvayu What's your opinion on this?

**Comment by suvayu** [comment]
I think it's good to split this.  About how to do it, in Python I would have gone with the separate package way, but I'm not sure what's best for Julia. To reduce the maintenance burden, maybe the answer is to recommend running TulipaPlots.jl from source.  

Something like:
- run TulipaEnergyModel.jl, and save results
- use TulipaPlots.jl to read saved results and make plots.

**Comment by clizbe** [comment]
Other question: Are we even going to be using the Julia plots in the long run? Or more likely linking DuckDB with a graph builder?

**Comment by suvayu** [comment]
If the DuckDB choice finalises, then it doesn't matter. Anyone could do whatever they want. Worst case: export to CSV/Parquet and do your thing. But ideally you would read it from DuckDB and plot (be it Python, Julia, JS).

**Comment by clizbe** [comment]
Covered by #451
