### ISSUE TITLE
Update western EU case to use 123 resolution

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#426]
### What and Why

Update input CSV data files for the EU case study to test speed and benchmark the model

**Comment by abelsiqueira** [comment]
This should include changing Neighbours' resolution.
Is there anything else required @datejada ?

**Comment by datejada** [comment]
@abelsiqueira, Yes, it should include changing Neighbours' resolution, and it will probably have more assets and flows than the current one.

**Comment by clizbe** [comment]
Related #112
