### ISSUE TITLE
Add most commonly used git commands in README.dev.md

### ISSUE THREAD

**Issue by gnawin** [TulipaEnergy/TulipaEnergyModel.jl#43]
The current README.dev.md includes a contributing workflow without git commands. It would be handy, especially for beginners like us, to have the git commands also included there.

I propose to add the commands from the notes https://hackmd.io/l1XUZ2n-QfSIbRl74FWk6g.

**Comment by clizbe** [comment]
Yes I believe this belongs in a GIT 101 section. And we can include our philosophy on rebasing, once decided in #30.
