### ISSUE TITLE
Apply specific "using" syntax

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#431]
_updated_
Apply @abelsiqueira's format to all files:

![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/8b159150-9f3f-4a8d-98b5-813406239659)

----------------------------------------------------------------------------
_original_
### What and Why

Tars suggested using `import` instead of `using`, we should see what difference it makes, the benefits and drawbacks.

**Comment by clizbe** [comment]
Answer from stackoverflow:
https://stackoverflow.com/questions/27086159/what-is-the-difference-between-using-and-import-in-julia-when-building-a-mod

> The import keyword [...] only operates on a single name at a time. It does not add modules to be searched the way using does. import also differs from using in that functions must be imported using import to be extended with new methods. [...] Functions whose names are only visible via using cannot be extended.

**Comment by datejada** [comment]
I think the remaining question is if that difference impacts Tulipa's performance. Maybe we should do a test to see the real impact of one way or the other.

**Comment by tarskul** [comment]
Just to clarify: 'using blabla' in Julia is very similar to 'from blabla import \*' in Python where the use of the wildcard (\*) is frowned upon (and for good reason).

It will not necessarily impact performance but it is a bad coding practice to implictly use functions from modules. Once the code expands, it will be more and more difficult for new developers to understand where the function is coming from. It is better to be explicit.

Additionally, being explicit is more future proof as you will avoid conflicts with functions from different modules with the same name. For example, in SpineOpt (or SpineInterface?) there was a function called 'parameter'. That was not an issue until JuMP decided to also add a function 'parameter' which, to this day, causes a problem with conflicting names (though we have reduced it to a warning).

I know 'using' is really common in Julia but I advise against it for the reasons above.

**Comment by abelsiqueira** [comment]
In more concrete terms, `using JuMP` right now imports all JuMP functions into the scope.
This means that we don't have to qualify functions (prepend functions with `JuMP`).

- `import JuMP` and then qualify functions (`JuMP.@variable`)
- Import functions explicitly like `import JuMP: JuMP, @variable` so we don't have to qualify.

The first option is more verbose but it makes it clear where things come from all the time, and the second is useful when you don't want to. @tarskul, for JuMP's `parameter`, if you use the first strategy, that won't be a problem.

I think the best compromise on what Tars mentioned and our usability is:

- Explicitly import JuMP macros
- Qualify everything else

This all assumes that we are not expanding any functions, which is the case and we probably won't in the (near) future.

@tarskul, I'm also curious if you have any good material in best practices for Julia.

**Comment by tarskul** [comment]
Unfortunately my "best practices" come from "experience".

However, I'm sufficiently interested in the project so at some point (if I find some time somewhere somehow) I may take a look at the code and I'll let you know if I notice something questionable.

Maybe I can also mention that a colleague of mine has once started an "advanced julia training course" but never finished it. Still, there is some valuable information there (e.g., if you want to go hardcore, you can check the difference between Int64[] and []): https://gitlab.kuleuven.be/UCM/esim-advanced-julia-training

**Comment by abelsiqueira** [comment]
Thanks.

**Comment by clizbe** [comment]
HOT GOSSIP
This is an option in Julia Formatter:
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/1aadfe28-58f8-442e-b8ff-4954aa113719)

**Comment by abelsiqueira** [comment]
After some exploration, I suggest `using Package: Package, some_stuff`.

- `using Package: Package` will import the module name, so it can be used for prefixing non-imported stuff.
- `using Package: some_stuff` will load `some_stuff`, which will permit using `some_stuff` without the prefix. I recommend this for obvious cases (such as JuMP's macros), or functions with explicit names (can't think of any right now).
- For some stuff, don't explicitly load it. Instead, when using it, prefix with the package name. For instance, `Graphs.edges`.

For most cases, `using` and `import` will work in the same way. The differences are:

- `using Package` without the `:` will load all `export`ed stuff. This is the main reason that `using` and `export` exist.
- `import Package` is the same as `using Package: Package`, i.e., it only loads the module name.
- If `Package` has a function `some_foo`, and our module also has `some_foo`, then `some_foo` needs to be explicitly `import`ed, otherwise it can't be defined.
  - This means that using `import Package: some_foo` actually allows implicit extension of `some_foo`, which can lead to undesired behaviour.
  - On the other hand, both `using Package` and `using Package: some_foo` will load `some_foo`, but won't allow defining `function some_foo` directly. Instead, you have to explicitly use `function Package.some_foo`.
  - For this reason, I am suggesting `using` instead of `import`.

Let me know what you think. Also pinging @suvayu and @datejada.

**Comment by suvayu** [comment]
> This means that using import Package: some_foo actually allows implicit extension of some_foo, which can lead to undesired behaviour.

Good catch!

> Instead, you have to explicitly use `function Package.some_foo`.

This sentence is confusing.  I guess you mean, `using Package: Package, some_foo` disallows overrides, so if we want to define that function, but not override the one from `Package`, we can do `using Package: Package` or `import Pacakge` and refer to the external function as `Package.some_foo` and be able to define our own `some_foo` without creating an override.

I would actually say in that case we should just  rename our `some_foo`.

Otherwise, agree with everything you say.

**Comment by abelsiqueira** [comment]
Explaining the second situation better: First, there are situations in which you would extend an existing name - none that apply to us so far - like defining `+` for a new type, or the `Base.show` definition that we have for `EnergyProblem` (file `structures.jl`).
 
So for those cases, you **want** to extend the function. So, for instance, for the function `is_binary` from JuMP. If we want to extend it for a new type `MyType`, we could do following:

```Julia
using JuMP: JuMP # or just using JuMP, or using JuMP: is_binary

function JuMP.is_binary(x :: MyType)
    return false
end
```

or

```Julia
import JuMP: is_binary

function is_binary(x :: MyType)
    return false
end
```

Both cases are readable, and you need to be explicit.

Second, there are situations where you don't want to extend, because actually it is something else, **but you want the same name**. Most common reason is that the function has a common or small name. In this case, just don't load `is_binary`:

```Julia
using JuMP: JuMP # don't load is_binary
# or import JuMP or import JuMP: JuMP, just don't load is_binary

function is_binary(x :: MyType)
    return false
end
```

If `is_binary` is called by some JuMP function with our type, it should error. `JuMP.is_binary` and `is_binary` will be different always.

The main difference in these cases, in my opinion, is intended behaviour. In the first, you're describing the behaviour that someone else defined. In the second, you're describing a new behaviour.

As a word of caution, you could, using this strategy, change a behaviour of some type that you haven't created. For instance, you could decide to change `Base.show` for `Int`. This is called **type piracy**, and is almost always a bad idea.

**Comment by suvayu** [comment]
Okay, that's clear. In this kind of situations I like being explicit. Your
proposal does that, so +1 from me.

-- 
Suvayu

**Comment by clizbe** [comment]
From Abel's last explanation, I prefer the first example:
```Julia
function JuMP.is_binary (x :: MyType)
  blah
end
```

I agree with Diego that in the second case we should just use a different name.

@abelsiqueira Do we need a new issue for this?

**Comment by abelsiqueira** [comment]
We can just change the title of the issue to something like "use explicit using syntax" or something. Or, if you prefer, convert this to discussion and create the issue.

**Comment by tarskul** [comment]
Hm, interesting stuff. I'm still wrapping my head around it, but it sounds good.

**Comment by datejada** [comment]
Hi! I found this package that figures out what implicit imports a Julia module relies on to make them explicit:

https://github.com/ericphanson/ExplicitImports.jl

Here is the discussion on Julia:

https://discourse.julialang.org/t/ann-explicitimports-jl-tooling-to-help-use-and-maintain-explicit-imports-in-your-package/110973

It seems easy to use, and we might want to use it when addressing this issue.
