### ISSUE TITLE
[BUG] - Parsing underscores in documentation

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#434]
### Description

Autodocs is parsing underscores into italics:
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/8e52f45c-e6b6-4b14-bda4-fa4dc8ee8165)

Source:
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/40774a7f-2d28-4e9e-a26c-292046846eb5)

### Reproduction steps

1. Read the docs shown above. Part of it is in italics.

Might be happening elsewhere... I'll do a thorough doc-readthrough in the future.

**Comment by datejada** [comment]
I have seen that in the SpineOpt repository, they solved like this **solve\_model**, the **\** does the trick. But I'm wondering if it is the best way or if the Documenter has an option to avoid it without this hack.

**Comment by clizbe** [comment]
Yeah good question. Adding a slash definitely makes it less readable in the code.

**Comment by clizbe** [comment]
The solution is to either:
1) Use backslash like you said
2) Indent the line so MD sees it as code (will depend on the line)
3) Use inline MD backticks: `what_ever`

Something to keep in mind when writing docstrings!
