### ISSUE TITLE
Tests fail on Mac with M1 chip

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#447]
### Description

Due to Cbc not supporting it: https://github.com/jump-dev/Cbc.jl/issues/193
I recommend we just drop Cbc of the tests. An alternative would be to check conditionally remove it based on `Sys.isapple()`.

### Reproduction steps

```bash
Just run the tests on a Mac with M1 chip.
```

### OS

Mac

**Comment by clizbe** [comment]
Having a specific conditional for this edge case seems messy.

I think as long as we're testing more than one it's fine to remove it.
For now: HIGHS, GLPK
Later add: Xpress

If users run into the problem later hopefully remember this is why.

**Comment by clizbe** [comment]
Maybe we could add a note to the user wherever they choose the solver? 🤔

**Comment by abelsiqueira** [comment]
This would be just for the test. The code itself remains the same. I would not touch anything on the code or documentation side about Cbc not being supported, since they could fix it eventually, and it creates precedent for informing the user about solver status. I think leaving HiGHS as default is enough, and eventually we can mention that we also use Xpress, if applicable.

Apart from that, I agree with removing it, rather than creating the conditional.

**Comment by abelsiqueira** [comment]
Well, I spoke too soon. The `Cbc` case is "necessary" for coverage. To be clearer, we have a case for `compute_dual_variables` that fails in a specific way for Cbc.
So removing Cbc requires either creating a fake test only to make coverage happy, which is not a good practice. So we either

- don't remove Cbc and use the conditional instead; or
- don't implement the check and risk the error appearing in a real situation; or
- stop having 100% coverage.

I recommend the first.

**Comment by clizbe** [comment]
Ah dang. Weird that there's a test that fails specifically in a way for Cbc...
But I guess that means we're supporting Cbc except for Mac M1, which is good. (Right?)

**Comment by abelsiqueira** [comment]
Well, Cbc is not in a great place, so it does have these corner cases. Luckily, HiGHS is becoming the de-facto open source MIP solver, so most people won't get into this random failures.
