### ISSUE TITLE
Refactor model creation using functions

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#452]
### What and Why

The function create_model is too long - and it's hard to profile. We should use functions to make the model creation modular.

### Related Issues

#489

**Comment by datejada** [comment]
Blocked by #255

**Comment by abelsiqueira** [comment]
I believe this is not blocked anymore. @datejada, confirm?

**Comment by datejada** [comment]
@abelsiqueira is correct; the changes in the model have been made, and the remaining issues in Epic #255 are related to documentation

**Comment by abelsiqueira** [comment]
Great idea, I think this is a nice one to pick because you can nibble at it, i.e., you can move one constraint to a function at a time. That way you can make sure that you don't have food poisoning - the tests are passing before moving to the next constraint - and you decide when to stop eating - create a pull request.
I hope all these eating metaphors don't make you throw up 😉

**Comment by abelsiqueira** [comment]
> @abelsiqueira First of all, did I mention I had a food reaction/poisoning a week ago and threw up my lunch? 😅 

😨 oops, you hadn't mentioned. I just have a natural ability to faux pas.

> Also, can you give an overview of the changes I should do? Do you mean to separate each constraint into a function or something else? Should I be looking for patterns where the same function can do multiple constraints?

What I would try to do is move constraints by "theme". Like all balance constraints inside a function, possibly in a separate file. This should keep the number of files to a manageable amount. I would not look into patterns at first, just moving things around.

I would do it like this to move the balance constraints, for instance:

- Create a new file (e.g., `src/constraints/balance.jl`)
- Create a function (e.g., `add_balance_constraints!(model, ...)` (arguments are still unknown)
- Select one of the balance constraints in `src/create-model.jl`, and cut-and-paste to the new function
- VSCode should warn you of undefined variables and functions, which you can add as parameters to the function
  - You should be able to define `x = model[:x]` for JuMP variables and expressions, so you don't need them in the function arguments. But the dataframe, for instance, will need to be passed to the function.
- Add a call to `add_balance_constraints!(model, ...)` in `src/create-model.jl`,
- Run the tests, and fix stuff until it passed
- Create a commit "move constraint ... to separate file/function" 
- Repeat until the function is done

That's what I'm thinking for now

**Comment by datejada** [comment]
> > @abelsiqueira First of all, did I mention I had a food reaction/poisoning a week ago and threw up my lunch? 😅
> 
> 😨 oops, you hadn't mentioned. I just have a natural ability to faux pas.
> 
> > Also, can you give an overview of the changes I should do? Do you mean to separate each constraint into a function or something else? Should I be looking for patterns where the same function can do multiple constraints?
> 
> What I would try to do is move constraints by "theme". Like all balance constraints inside a function, possibly in a separate file. This should keep the number of files to a manageable amount. I would not look into patterns at first, just moving things around.
> 
> I would do it like this to move the balance constraints, for instance:
> 
> * Create a new file (e.g., `src/constraints/balance.jl`)
> * Create a function (e.g., `add_balance_constraints!(model, ...)` (arguments are still unknown)
> * Select one of the balance constraints in `src/create-model.jl`, and cut-and-paste to the new function
> * VSCode should warn you of undefined variables and functions, which you can add as parameters to the function
>   
>   * You should be able to define `x = model[:x]` for JuMP variables and expressions, so you don't need them in the function arguments. But the dataframe, for instance, will need to be passed to the function.
> * Add a call to `add_balance_constraints!(model, ...)` in `src/create-model.jl`,
> * Run the tests, and fix stuff until it passed
> * Create a commit "move constraint ... to separate file/function"
> * Repeat until the function is done
> 
> That's what I'm thinking for now

I agree with the procedure, but regarding the classification of how to split, I prefer to discuss it with the whole team before continuing. `balance` seems natural, but we have two structures for time (inter- and -intra) and maybe splitting by that criteria will make more sense (or not).

**Comment by clizbe** [comment]
After some discussion we've decided to group primarily by asset type, to match the documentation and be clear to users.
