### ISSUE TITLE
Update the logo

### ISSUE THREAD

**Issue by greg-neustroev** [TulipaEnergy/TulipaEnergyModel.jl#460]
### What and Why

The current logo looks more like a box and less like a tulip.

**Comment by greg-neustroev** [comment]
This is the latest iteration on logo ideas. @clizbe, @datejada and I like the second version the best, I think. It works on both light and dark background, and in smaller sizes too.

![Tulipa](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/32451432/44169815-c497-44d8-bac5-870479d556a4)

**Comment by greg-neustroev** [comment]
@abelsiqueira @suvayu @gnawin @g-moralesespana your opinions?

**Comment by greg-neustroev** [comment]
![Tulipa_small](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/32451432/c352e196-a964-4b4a-ba4c-d61c056a9983)

same logos but scaled down to see how they appear in a smaller resolution

**Comment by g-moralesespana** [comment]
I like the small change that makes it look more like a tulip, and it is still a convex region ;). I do not know about the other, but I like the two in the middle best.

**Comment by abelsiqueira** [comment]
I like number 2 the most. Are we voting or ranking or grading.

**Comment by datejada** [comment]
My vote is for the second one, too 😄

**Comment by gnawin** [comment]
Number 2 or 3 for me.

**Comment by clizbe** [comment]
We're voting! @suvayu you're the only one missing. :)

**Comment by clizbe** [comment]
New question, do we want the toned-down yellow or the original BRIGHT yellow?  I think with the new design the bright might look nice. 🙃

**Comment by clizbe** [comment]
Also, where do we put the name ("Tulipa" or "TULIPA"or "TulipaEnergyModel.jl") for the bigger logo?

**Comment by datejada** [comment]
If we include a name, I prefer TulipaEnergyModel or TulipaEnergy (as the organization name in GitHub). Tulipa alone may not be associated with energy, and all uppercase letters may seem like an acronym.

**Comment by abelsiqueira** [comment]
+1 TulipaEnergy

**Comment by g-moralesespana** [comment]
I am also ok with TulipaEnergy or TulipaEnergyModel, but whatever it is let's not use capital letter for the full name because the it looks like an acronym.

**Comment by greg-neustroev** [comment]
Needs updating in the docs
