### ISSUE TITLE
Consider refactoring the names of the incoming and outgoing flows

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#468]
### What and Why

In the data frames, the names of the incoming and outgoing flows include the resolution (e.g., `incoming_flow_lowest`, `outgoing_flow_highest`). Since these columns are parts of a dataframe named according to the resolution, it is not necessary to name them like this.
This will also allow removing a condition on `add_expression_terms!` that checks for `use_highest_resolution` to define the name.

This might be better implemented after #344.

**Comment by abelsiqueira** [comment]
@datejada, can you give your opinion on this?

**Comment by datejada** [comment]
I agree, the df name will be enough to know that the flows are in the lowest or highest resolution.

**Comment by abelsiqueira** [comment]
Better to wait until #456
