### ISSUE TITLE
Consider using time_block instead of B internally

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#470]
### What and Why

Some places using time blocks in the code use `B` (like `for B in graph[u, v].partitions[rp]`). Some use `time_block`. Since `B` is not always clear, as opposed to `a in A` or `a in labels(graph)`, which is a bit more intuitive, I recommend using `time_block` instead.

**Comment by clizbe** [comment]
I agree - we should be consistent (not name the same thing twice) and time_block is more clear.

**Comment by abelsiqueira** [comment]
Better to wait until #456
