### ISSUE TITLE
Explore how to merge hub and consumer

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#477]
### What and Why

@datejada and @g-moralesespana, please check.

**Comment by clizbe** [comment]
While I think we should make it as compact as possible, we should be careful in naming so the user isn't confused.

**Comment by clizbe** [comment]
After some discussion we decided:
Technically we could merge EVERYTHING into one equation, but we specifically broke it out for readability.
Therefore we prefer to keep them separate, to be more clear for the user.

However, we would like to wait until proper ESDL integration to see how they handle it - and do whatever is easier to work with ESDL.

**Comment by clizbe** [comment]
I'm learning more about ESDL through another project, so it might help with this.
In general, Consumers can't have Outports - so that's something we'll need to look into.
And they have a "network" or something asset so that might correspond to a Hub.

**Comment by clizbe** [comment]
Decided to keep them separate.
- Easier for user
- We separated asset types for a reason
- We can put angles everywhere to avoid extra variables
