### ISSUE TITLE
Use dataframes instead of dict for RP weight matrix

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#495]
### What and Why

Found this in `io.jl`.
Might already be done? @abelsiqueira  

    # TODO: Depending on the outcome of issue #294, this can be done more efficiently with DataFrames, e.g.,
    # combine(groupby(rp_mapping_df, :rep_period), :weight => sum => :weight)

### Related Issues

#294

**Comment by abelsiqueira** [comment]
That was added by @greg-neustroev in b975ece8.
I don't think it was done, or that it can be done at the moment.
I think it also depends on the input changes. Maybe @suvayu and @greg-neustroev can comment.

**Comment by abelsiqueira** [comment]
#294 was related to the data frames implementation, but we haven't changed the input. After TIO, it might apply or not. Either way, it might benefit from becoming an issue, if @greg-neustroev wants to transform that comment into one.

**Comment by datejada** [comment]
See also comments from #688 on this issue
