### ISSUE TITLE
Documentation for Solution in how-to-use is out-of-date

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#506]
### What and Why

Solution was changed in #494, and at least since then, the description of the solution in the Solution section in how-to-use is wrong.

**Comment by clizbe** [comment]
I believe the tutorial is out of date. Shouldn't this say "energy_problem.solution?"



![Image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/8eab4679-1493-4433-afe4-75f8076a5009)

**Comment by clizbe** [comment]
@abelsiqueira Can you help me finish this off? :)

**Comment by abelsiqueira** [comment]
Hi @clizbe, both work in that case because `solution` is also returned by `solve_model!`, but it could be changed to use `energy_problem.solution` as well.

The main differences from the old Solution to the new are:

- Now `Solution` is a proper structure, being stored inside the `energy_problem` (it was a NamedTuple) (see structures.jl);
- the fields `flows` and `storage_level_*` are now vectors, indexed linearly following the dataframes `energy_problem.dataframes[:flows]`, `:lowest_storage_level_intra_rp`, and `:storage_level_inter_rp`
- the dual variables are also stored in a Dict inside Solution.

The (rest of the) tutorial code should be correct, if you want to see how it is being used. In the `how-to-use#Solution` section I just point to the `@ref solution-tutorial` for an actual example of how-to-use, to avoid explaining it twice.

Let me know if you want more tips or a deeper explanation.

**Comment by abelsiqueira** [comment]
The doctoring of `solve_model` is also wrong.

**Comment by clizbe** [comment]
Yeah I noticed that too. Thought I'd update it once I have the truth. :)
Thanks I think your comment cleared everything up.
