### ISSUE TITLE
Create new files to store the different kinds of profiles

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#516]
The current structure of the `assets-profile.csv` file assumes that all profiles are associated with availability profiles, which is true in most cases. Still, for energy storage, the profile is commonly associated with the energy inflows the asset can get.

For the proposed solution, see discussion #517

**Comment by abelsiqueira** [comment]
We decided to have the following Tables:

- `asset-profiles` (and similar for flows)
  - column `asset` with the asset name
  - column `profile_type` with the profile type
  - column `profile_id` with the profile id for that specific type
- `<type>-profiles`, e.g., `availability-profiles`, `demand-profiles`, and `inflows-profiles`
  - column `id` with the id of the profile type
  - column `rep_period` with the representative period
  - column `time_step`
  - column `value`

For this issue, we are going to change the CSV files and the revelant functions and data structures.
