### ISSUE TITLE
Improve the pre-filled contents of the csv files

### ISSUE THREAD

**Issue by gnawin** [TulipaEnergy/TulipaEnergyModel.jl#520]
### What and Why

Add something meaningful to the first row in our input csv files, i.e., `assets-partitions.csv`, `flows-partitions.csv`, and `rep-periods-mapping.csv`. Please refer to #518 for details.

### Related Issues

Discussion #518

**Comment by datejada** [comment]
Issue #522 will consider the changes proposed here for the input files
