### ISSUE TITLE
Create new variables and constraints to have a max/min energy outgoing flow for assets, using the base periods

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#526]
### Description

**This epic issue is part of the different levels of detail in the operation module for M3.**

The base periods allow for inter-representative period constraints since they recover chronological information, e.g., having maximum/minimum total energy flow for other types of assets (e.g., producers).

**Example: A gas contract with a max/min monthly limit**: if we have base periods 1...365, i.e., for each day of the year, then with a partition that represents a monthly time block (i.e., 1x31+1x28+1x31+1x30...), then we can set maximum/minimum limits for the monthly gas flow.

For this issue you can use as a reference the existing `storage_level_inter_rp` variable, constraints, and dataframes, since their temporal structure should be similar.

### Sub issues for assets with outgoing flows (i.e., producers, conversion, and storage)

- [x] #655
- [x] #657
  - Create the dataframe from the partition definitions for the variables and constraints. If there is no defined profile, there should be no constraints. We should apply this type of constraint if we have the data; otherwise, they are superfluous.
  - ~Create the energy variables e.g,. `asset_outgoing_energy_flow_inter_rp` (or a better name, and also maybe for the incoming energy flow, depending on the asset)~ No need of extra variables here
  - Create the constraints for the maximum and minimum energy limit
  - Update the outputs of the model
- [x] #659 
- [x] #662
  - Example
  - How-to
  - Mathematical documentation
- [x] #652

Add anything else that you can think of during the development of the epic...happy coding! 😄

**Comment by clizbe** [comment]
For my own clarification, this is for operational considerations in the investment decision.
For instance, setting a min production of green hydrogen for the total year.
