### ISSUE TITLE
flows-data needs a is_seasonal column (or remove base partitions of flows)

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#537]
### What and Why

While working on #475, I noticed that `flows-data.csv` does not `is_seasonal`, however, there are base-partitions for flows.
I want to set the base partitions from the `is_seasonal` column (for assets and flows), instead of implicitly depending on what is defined in the partitions file. So it would make sense to create this column.
On the other hand, it looks like we don't need base partitions for flows.
One of the two actions seems reasonable:

- Remove everything related to base partitions in the flows
- Add a is_seasonal column to the data

cf. @datejada

**Comment by datejada** [comment]
@abelsiqueira, on second thought...for the use cases on #526, we can use the `is_seasonal` for other types of assets, and then we don't need to create the structure on the flows. I think it is cleaner, and we avoid having extra files. So, I choose removing 😄 

If we change our minds when tackling #526, we can always put them back 😉
