### ISSUE TITLE
Use is_seasonal to define the base partitions

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#538]
### What and Why

Instead of implicitly using the base-periods-partitions file.

### Possible Drawbacks

We have to implement the implicit definition of the undeclared `is_seasonal` assets/flows to be `:uniform,1`, as we do with representative periods.

### Related Issues

Blocked by #537

**Comment by abelsiqueira** [comment]
Another drawback is that typos can lead to error behaviour, since this also introduces implicit behaviour. One possibility is to force both:

- All is_seasonal need a entry in the partitions file
- All entries in the partitions file have to be is_seasonal.

This can be implemented in this scope, but it is related to #461 as well. I recommend implement here now, since it doesn't hurt.

**Comment by datejada** [comment]
The parameter `is_seasonal` should trigger the inter-rp constraints (defined on the base periods). I'm also thinking about issue #526, so:

- if `is_seasonal = false`, no inter-rp constraints are created
- if `is_seasonal = true` inter-rp constraints are created, the partition definitions will be read from the file.
- if `is_seasonal = true` and there are no partition definitions, the default partition should be `:uniform,1,`

@abelsiqueira, does this description make it more clear?

**Comment by abelsiqueira** [comment]
That's great, thanks
