### ISSUE TITLE
Consider using Symbol instead of String for columns and other identifier

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#540]
### What and Why

For instance, an `asset` would be a `Symbol` instead of a `String`.
Some keys of dictionaries are also Strings, such as `rep` and `base`.

More info on symbol vs string: https://bkamins.github.io/julialang/2022/08/05/symbol.html

**Comment by datejada** [comment]
I like this proposal; It is something that we should do at some point since symbols have advantages over strings. It may be an excellent moment to do it before the release of the M1.

@abelsiqueira, Do you know an easy way to do this?

**Comment by abelsiqueira** [comment]
I'll figure out
