### ISSUE TITLE
Separate the reading and processing in the IO

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#544]
### What and Why

Currently, the reading of CSV processes a lot of stuff returning the graph structure, the representative periods structure, and the base periods structure. We should have an intermediate step that just reads the data into dataframes and a second (or more) function(s) will process dataframes into something else.

Things to keep in mind:

- Reading will move to TulipaIO.jl
- Many structures will change to DataFrames 
- We want to allow manual input

**Comment by clizbe** [comment]
@suvayu "Data validation of whether columns are correctly named etc should be within TEM, not TIO. And it should be concentrated in one spot in the workflow, not spread out all over the place."
