### ISSUE TITLE
Improve data of Norse case tutorial

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#574]
### What and Why

In the tutorial there are a lot of arrays that return as 0s - which is correct but boring. It would be more interesting/useful if the arrays had some values in them.

### Possible Drawbacks

This would change the data of the Norse case, which would change test results.

**Comment by datejada** [comment]
This is only one nearly the end

**Comment by clizbe** [comment]
Eh it's fine.
