### ISSUE TITLE
Add investment methods for energy storage assets

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#575]
### Description

As part of the M2 and the developments for the investment module for seasonal & non-seasonal storage, we need to improve the storage investment representation. We must create a new parameter (e.g., `storage_investment_method`) to select different investment methods in storage assets (the following is a guide, please review it before starting and think about more constraints/variables/parameters we might need):

1. `storage_investment_method = "use_fixed_ratio"`: This is the implementation in version 0.8.0 and below.
   - variables: $v^{\text{inv}}_{a}$ -> investment in MW
   - parameters:
     - $p^{\text{energy to power ratio}}_a$ -> fixed ratio between the stored capacity (MWh) and the charge/discharge capacity (MW)
     - $p^{\text{inv cost}}_{a}$ -> investment cost per unit of the asset MW/unit
     - $p^{\text{inv limit}}_{a}$ -> investment limit (potential) of the asset MW
     - $p^{\text{capacity}}_{a}$ -> capacity of a unit of investment of the asset MW/unit 
   - objective function: we only pay the investment cost of the power part 
   - constraints (look at the documentation of v0.8.0):
     - maximum storage level limit
     - maximum investment limit

2. `storage_investment_method = "use_storage_energy"`
   - variables:
     - $v^{\text{inv}}_{a}$ -> investment in MW
     - $v^{\text{inv energy}}_{a}$ -> investment in MWh
   - parameters:
     - $p^{\text{inv cost}}_{a}$ -> investment cost per unit of the asset MW/unit
     - $p^{\text{inv cost energy}}_{a}$ -> investment cost per unit of energy the asset MWW/unit
     - $p^{\text{inv limit}}_{a}$ -> investment limit (potential) of the asset MW
     - $p^{\text{inv limit energy}}_{a}$ -> investment limit on energy (potential) of the asset MWh
     - $p^{\text{capacity}}_{a}$ -> capacity of a unit of investment of the asset MW/unit 
     - $p^{\text{capacity energy}}_{a}$ -> capacity of a unit of investment of the asset MW/unit 
   - objective function: we pay for both the power investment and the storage investment
   - constraints:
     - maximum storage level limit 
     - maximum investment limit (look at the documentation of v0.8.0)
     - maximum investment limit for storage energy 

**NOTE**: The names are suggestions. Consider changing them if there is a better option.

### Sub issues

- [x] Define the mathematical formulation (conceptual part) - review the ones in the previous section and write the equations in this issue
- [x] #600
- [x] #604
- [x] #626
- [x] #628

**Comment by gnawin** [comment]
Define the math here

1. `storage_investment_method = "use_fixed_ratio"`: This is the implementation in version 0.8.0 and below.
   - variables: $v^{\text{inv}}_{a}$ -> investment in MW
   - parameters:
     - $p^{\text{energy to power ratio}}_a$ -> fixed ratio between the stored capacity (MWh) and the charge/discharge capacity (MW)
     - $p^{\text{inv cost}}_{a}$ -> investment cost per unit of the asset MW/unit
     - $p^{\text{inv limit}}_{a}$ -> investment limit (potential) of the asset MW
     - $p^{\text{capacity}}_{a}$ -> capacity of a unit of investment of the asset MW/unit 
   - objective function: we only pay the investment cost of the power part (__do we need to consider the energy part?__) , i.e., the only relevant term is 
```math
\begin{aligned}
assets\_investment\_cost = \sum_{a \in \mathcal{A}^{\text{i}}} p^{\text{inv cost}}_{a} \cdot p^{\text{capacity}}_{a} \cdot v^{\text{inv}}_{a} 
\end{aligned}
```

   - constraints (look at the documentation of v0.8.0):
     - maximum storage level limit
     - maximum investment limit

#### Intra-temporal Constraint for Maximum Storage Level Limit
```math
v^{\text{intra-storage}}_{a,k,b_k} \leq p^{\text{max intra level}}_{a,k,b_k} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{energy to power ratio}}_a \cdot p^{\text{init capacity}}_{a} \cdot v^{\text{inv}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{s}} \setminus \mathcal{A}^{\text{ss}}, \forall k \in \mathcal{K},\forall b_k \in \mathcal{B_k}
```
#### Intra-temporal Constraint for Minimum Storage Level Limit
```math
v^{\text{intra-storage}}_{a,k,b_k} \geq p^{\text{min intra level}}_{a,k,b_k} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{energy to power ratio}}_a \cdot p^{\text{init capacity}}_{a} \cdot v^{\text{inv}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{s}} \setminus \mathcal{A}^{\text{ss}}, \forall k \in \mathcal{K},\forall b_k \in \mathcal{B_k}
```
#### Inter-temporal Constraint for Maximum Storage Level Limit
```math
v^{\text{inter-storage}}_{a,p} \leq p^{\text{max inter level}}_{a,p} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{energy to power ratio}}_a \cdot p^{\text{init capacity}}_{a} \cdot v^{\text{inv}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{ss}}, \forall p \in \mathcal{P}
```
#### Inter-temporal Constraint for Minimum Storage Level Limit
```math
v^{\text{inter-storage}}_{a,p} \geq p^{\text{min inter level}}_{a,p} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{energy to power ratio}}_a \cdot p^{\text{init capacity}}_{a} \cdot v^{\text{inv}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{ss}}, \forall p \in \mathcal{P}
```
#### Maximum Investment Limit for Assets
```math
v^{\text{inv}}_{a} \leq \frac{p^{\text{inv limit}}_{a}}{p^{\text{capacity}}_{a}} \quad
\\ \\ \forall a \in \mathcal{A}^{\text{i}}
```

2. `storage_investment_method = "use_storage_energy"`
   - variables:
     - $v^{\text{inv}}_{a}$ -> investment in MW
     - $v^{\text{inv energy}}_{a}$ -> investment in MWh
   - parameters:
     - $p^{\text{inv cost}}_{a}$ -> investment cost per unit of the asset MW/unit
     - $p^{\text{inv cost energy}}_{a}$ -> investment cost per unit of energy the asset MWW/unit
     - $p^{\text{inv limit}}_{a}$ -> investment limit (potential) of the asset MW
     - $p^{\text{inv limit energy}}_{a}$ -> investment limit on energy (potential) of the asset MWh
     - $p^{\text{capacity}}_{a}$ -> capacity of a unit of investment of the asset MW/unit 
     - $p^{\text{capacity energy}}_{a}$ -> capacity of a unit of investment of the asset MW/unit 
   - objective function: we pay for both the power investment and the storage investment
   - constraints:
     - maximum storage level limit 
     - maximum investment limit (look at the documentation of v0.8.0)
     - maximum investment limit for storage energy 

**NOTE**: The names are suggestions. Consider changing them if there is a better option.

**Comment by gnawin** [comment]
New math 
`storage_investment_method = "use_storage_energy"`
   - variables:
     - $v^{\text{inv}}_{a}$ -> investment in MW
     - $v^{\text{inv energy}}_{a}$ -> investment in MWh
   - parameters:
     - $p^{\text{inv cost}}_{a}$ -> investment cost per unit of the asset MW/unit
     - $p^{\text{inv cost energy}}_{a}$ -> investment cost per unit of energy the asset MWh/unit
     - $p^{\text{inv limit}}_{a}$ -> investment limit (potential) of the asset MW
     - $p^{\text{inv limit energy}}_{a}$ -> investment limit on energy (potential) of the asset MWh
     - $p^{\text{capacity}}_{a}$ -> capacity of a unit of investment of the asset MW/unit 
     - $p^{\text{energy}}_{a}$ -> energy of a unit of investment of the asset MWh/unit 
   - objective function: we pay for both the storage power investment and energy investment
 ```math
\begin{aligned}
assets\_investment\_cost = \sum_{a \in \mathcal{A}^{\text{i}}} p^{\text{inv cost}}_{a} \cdot p^{\text{capacity}}_{a} \cdot v^{\text{inv}}_{a} +  \sum_{a \in \mathcal{A}^{\text{i}} \cap \mathcal{A}^{\text{s}} } p^{\text{inv cost energy}}_{a} \cdot p^{\text{energy}}_{a} \cdot v^{\text{inv energy}}_{a}  
\end{aligned}
```

   - constraints:
     - maximum storage level limit 
     - maximum investment limit 
     - maximum investment limit for storage energy

### Modified existing constraints (from v0.8):

#### Intra-temporal Constraint for Maximum Storage Level Limit
```math
v^{\text{intra-storage}}_{a,k,b_k} \leq p^{\text{max intra level}}_{a,k,b_k} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{inv cost energy}}_a \cdot v^{\text{inv energy}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{s}} \setminus \mathcal{A}^{\text{ss}}, \forall k \in \mathcal{K},\forall b_k \in \mathcal{B_k}
```
#### Intra-temporal Constraint for Minimum Storage Level Limit
```math
v^{\text{intra-storage}}_{a,k,b_k} \geq p^{\text{min intra level}}_{a,k,b_k} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{inv cost energy}}_a \cdot v^{\text{inv energy}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{s}} \setminus \mathcal{A}^{\text{ss}}, \forall k \in \mathcal{K},\forall b_k \in \mathcal{B_k}
```
#### Inter-temporal Constraint for Maximum Storage Level Limit
```math
v^{\text{inter-storage}}_{a,p} \leq p^{\text{max inter level}}_{a,p} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{inv cost energy}}_a \cdot v^{\text{inv energy}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{ss}}, \forall p \in \mathcal{P}
```
#### Inter-temporal Constraint for Minimum Storage Level Limit
```math
v^{\text{inter-storage}}_{a,p} \geq p^{\text{min inter level}}_{a,p} \cdot (p^{\text{init storage capacity}}_{a} + p^{\text{inv cost energy}}_a \cdot v^{\text{inv energy}}_{a}) \quad
\\ \\ \forall a \in \mathcal{A}^{\text{ss}}, \forall p \in \mathcal{P}
```
#### Maximum Investment Limit for Assets
```math
v^{\text{inv}}_{a} \leq \frac{p^{\text{inv limit}}_{a}}{p^{\text{capacity}}_{a}} \quad
\\ \\ \forall a \in \mathcal{A}^{\text{i}}
```

### New constraints (from v0.8):
#### Maximum Investment Limit for Assets
```math
v^{\text{inv energy}}_{a} \leq \frac{p^{\text{inv limit energy}}_{a}}{p^{\text{capacity energy}}_{a}} \quad
\\ \\ \forall a \in \mathcal{A}^{\text{i} \cap \mathcal{A}^{\text{s}}
```

**Comment by gnawin** [comment]
@datejada could you check the new design? If it looks okay, I can continue to work on merge the PRs 😄 . Thanks!

**Comment by datejada** [comment]
All issues from this epic have been completed 🚀
