### ISSUE TITLE
Improve investment limit constraint

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#577]
### What and Why

For the maximum investment limit for assets and flows, here:

https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/main/src/constraints/investment.jl

We need to add a condition for the right-hand side (RHS) of the investment limit constraints, such that if the parameter `investment_integer` is `true`, then we limit it to the lowest integer value of the fraction using a ceiling function, to guarantee that the limit is an integer. Otherwise, it can stay as it is today.

### Possible Drawbacks

- Be careful of the codecov! Since we are creating a new condition. 
- Run the benchmark to double-check any potential performance issues.

**Comment by datejada** [comment]
> I suppose you meant using a floor function instead of a ceil function, because we want to get the lower bound of the float, otherwise it may exceed the limit. Right?

Nice catch 😄 yeap, we want the floor function instead of ceil. Thanks!

**Comment by gnawin** [comment]
@datejada I found in `create_model.jl` the following code:

```
    ### Integer Investment Variables
    for a in Ai
        if graph[a].investment_integer
            JuMP.set_integer(assets_investment[a])
        end
    end

    for (u, v) in Fi
        if graph[u, v].investment_integer
            JuMP.set_integer(flows_investment[(u, v)])
        end
    end
```

To me this already ensures that we only have integer variables when necessary, so it becomes unnecessary to do the check for the investment limit. Right?
