### ISSUE TITLE
Add basic version of unit commitment and ramping constraints

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#581]
### Description

Create methods to have two levels of detail for the unit commitment:
- no unit commitment
- basic/simple version

**NOTE: The more complex version of the unit commitment (i.e., tight and compact) will be implemented in 2025!**

Also, we need to create methods to have the possibility of having ramping constraints or not.

Use the formulation here as a reference:

https://www.overleaf.com/project/6454fde7fdf7f1c73ceeb2a0

### Sub issues (edit and create relevant issues as they are needed)

- [x] Write the formulation in Tulipa jargon for the code (be careful with the multiple in/out flows)
- [x] Write the constraints with the flexible temporal resolution for the unit commitment variables
- [x] #724
- [x] #756
- [x] #763  
- [x] #752
- [x] #750
- [x] #772
- [x] #770

**Comment by datejada** [comment]
Starting in July

**Comment by datejada** [comment]
Take @gzclarence formulation from the "Fully Flexible Temporal Resolution for Energy System Optimization Using Index Aggregation" paper for the unit commitment and ramping constraints using flexible temporal resolution. By July, a pre-print should be publicly available; in the meantime, ask Zhi for details.

**Comment by datejada** [comment]
# Basic unit commitment version

$v^{\text{on}}_{a,k,b_k}$: Number of units ON of asset $a$ in representative period $k$ and timestep block $b_k$ [N]

```math
\sum_{f \in \mathcal{F}^{\text{out}}_a} v^{\text{flow}}_{f,k,b_k} \leq p^{\text{availability profile}}_{a,k,b_k} \cdot \left(p^{\text{init capacity}}_{a} + p^{\text{capacity}}_{a} \cdot v^{\text{inv}}_{a} \right)  \quad
\\ \\ \forall a \in \mathcal{A}^{\text{cv}} \cup \mathcal{A}^{\text{p}}, \forall k \in \mathcal{K},\forall b_k \in \mathcal{B_k}
```

**Comment by datejada** [comment]
@g-moralesespana please review the equations above for the basic/simple unit commitment method we will implement in the model. The full list of symbols and variables is available in the [documentation](https://tulipaenergy.github.io/TulipaEnergyModel.jl/dev/formulation/). Notice that for the sake of simplicity, here we don't show the flexible temporal resolution stuff (although, for this case, we defined that all the constraints will be in power, so the duration of the `temporal_blocks` won't affect).

**Comment by clizbe** [comment]
@datejada I got an Overleaf account, but still don't have access to your link:


![Image](https://github.com/user-attachments/assets/498bca77-5a26-42d2-abdf-77c4d6275b5a)

**Comment by clizbe** [comment]
Is there a difference between using something like this:

```
if row.asset ∈ Auc
    FOO
else row.asset non-Auc
    BAR
```


or this:
``` 
cases = [Auc, non-Auc]
for case in cases
    FOO BAR
end
```

Okay while writing the question I think I figured it out.
The first is if you want different logic depending on the selection.
The second is you want the same logic for everyone, but with different parameters/options depending on the selection.

@abelsiqueira Is that right? (Dunno if the question even makes sense. I ran into "cases" in the intra_rp_constraints in create_model and thought maybe it could be used to apply constraints to specific assets (where we currently use a subset such as Ft or Auc).

**Comment by abelsiqueira** [comment]
@clizbe, yes the second snippet is the same logic for everyone.

**Comment by clizbe** [comment]
@datejada 
Is the "Limit to the units on (i.e., commitment) variable:" constraint supposed to have p_init_units or is it actually p_init_capacity?

**Comment by clizbe** [comment]
@datejada To use _e flow above min_ for timeblock -1 (second term in max ramp-up rate limit) - should I create a second expression to calc this as needed or should _e flow above min_ be stored somewhere that I can access the previous timeblock?

**Comment by datejada** [comment]
> > We want to use a different method for ramping. So, we can have:
> > 
> > * No UC, No ramping
> > * No UC, Yes ramping
> > * Yes UC, No ramping
> > * Yes UC, Yes ramping
> 
> @datejada Does this mean I also need to add a method for ramping (not listed above)?

@clizbe Correct!, it is not updated in the first part of this issue. We need something like $A^{ramp}$ for the assets with a ramp method. Then, the formulation should be updated to apply only the assets in each case. Give it a try to update the formulation, and I can review it afterwards 😉

**Comment by datejada** [comment]
> @datejada To use _e flow above min_ for timeblock -1 (second term in max ramp-up rate limit) - should I create a second expression to calc this as needed or should _e flow above min_ be stored somewhere that I can access the previous timeblock?

For the first implementation, let's assume we apply the constraint for timeblock > 1 (so we don't deal with that situation now). There are simple and fancy ways to deal with that, but the easy is to start creating the constraint after the first timeblock (so you don't have the problem of the previous one)

**Comment by datejada** [comment]
> @datejada Is the "Limit to the units on (i.e., commitment) variable:" constraint supposed to have p_init_units or is it actually p_init_capacity?

@clizbe Nice catch! we need to add the bound for the units on. It should be <= existing units + investment variable

where:
existing units => can be determined from the parameters `capacity` and `initial_capacity` 
investment variable => assets_investment[a]

There are a couple of things to consider here, but we can comment on later. This is the general idea

**Comment by clizbe** [comment]
> > @datejada To use _e flow above min_ for timeblock -1 (second term in max ramp-up rate limit) - should I create a second expression to calc this as needed or should _e flow above min_ be stored somewhere that I can access the previous timeblock?
> 
> @clizbe For the first implementation, let's assume we apply the constraint for timeblock > 1 (so we don't deal with that situation now). There are fancy ways to deal with that (e.g., cycling constraints), but the easy is to start creating the constraint after the first timeblock (so you don't have the problem of the previous one) @g-moralesespana, Do you have any extra thoughts?

Okay! But that doesn't answer my question. Should I be calculating two parameters (t and t-1) or just one (all t) and referencing t-1?
Because I think with my current implementation it's easier to calculate them separately, but maybe that's inefficient.

**Comment by datejada** [comment]
> > > @datejada To use _e flow above min_ for timeblock -1 (second term in max ramp-up rate limit) - should I create a second expression to calc this as needed or should _e flow above min_ be stored somewhere that I can access the previous timeblock?
> > 
> > 
> > @clizbe For the first implementation, let's assume we apply the constraint for timeblock > 1 (so we don't deal with that situation now). There are fancy ways to deal with that (e.g., cycling constraints), but the easy is to start creating the constraint after the first timeblock (so you don't have the problem of the previous one) @g-moralesespana, Do you have any extra thoughts?
> 
> Okay! But that doesn't answer my question. Should I be calculating two parameters (t and t-1) or just one (all t) and referencing t-1? Because I think with my current implementation it's easier to calculate them separately, but maybe that's inefficient.

So, two things here. First, you don't need a second expression, please take a look to the first constraint in the storage file https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/main/src/constraints/storage.jl
It has the structure of t-1 in the storage level.
Second, to avoid and error for the first timeblock (because timeblock before t=1 does not exist) you need to write the constraint starting from the second timeblock (then the previous one, i.e., t=1, exists).

The first thing is the answer to your question; the second thing is what I thought you were asking at the beginning 😝

**Comment by datejada** [comment]
> > > @datejada Is the "Limit to the units on (i.e., commitment) variable:" constraint supposed to have p_init_units or is it actually p_init_capacity?
> > 
> > 
> > @clizbe Nice catch! we need to add the bound for the units on. It should be <= existing units + investment variable
> > where: existing units => can be determined from the parameters `capacity` and `initial_capacity` investment variable => assets_investment[a]
> > There are a couple of things to consider here, but we can comment on later. This is the general idea
> 
> I'm still not sure what you mean. Do we consider Units to be a subdivision of Capacity? Like there are 2 Units with 10 Capacity each so we have 20 Capacity?

Yes, but after reading your question and looking at the input data, maybe we can change it a bit the input data to make it clearer and easier for the users. Please take a look on how is the input data for the units in INES specification.
What we need is either initial units and some capacity to determine the initial capacity or some initial capacity and a capacity per unit, and then we can calculate the initial number of units. We should look at the proposal in INES and also what makes more sense for the users.
I will add the constraint to the formulation part of this issue to make it clear in math.

**Comment by clizbe** [comment]
@datejada The "flow above min operating point >= 0" constraint is for the subset Auc_basic.
Does that mean the constraint only applies to Auc_basic and not (in the future) to Auc_advanced?

**Comment by datejada** [comment]
> @datejada The "flow above min operating point >= 0" constraint is for the subset Auc_basic. Does that mean the constraint only applies to Auc_basic and not (in the future) to Auc_advanced?

We will use it in the future for the Auc_advanced, but since it is not in place yet, it is OK that it only applies to the Auc_basic for now. In the future, it will apply if any Auc method is selected.

**Comment by datejada** [comment]
All tasks have been completed 🚀
