### ISSUE TITLE
Benchmark workflow does not work for PRs from forks

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#59]
The Benchmark workflow is supposed to run the benchmarks and comment the resources in the PR. However, it needs permissions that can't be granted if the PR is from a fork.

The "straightforward but not simple solution" would be to change our workflow entirely and use branches in the main repo instead of forks.

@suvayu also posted the idea below:
 
> IMO this should be a bot, and a cron job.  Bot to manually trigger it in a PR, and cron that checks performance regression, say, once a week.

_Originally posted by @suvayu in https://github.com/TNO-Tulipa/TulipaBulb.jl/issues/50#issuecomment-1706483823_

@suvayu, do you know how to set that up, do you know if it works without permissions?

**Comment by suvayu** [comment]
The cron part is easy.

To trigger from comments, I have a possible implementation in mind using [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch), but it's a bit fidgety.

In the past, I've seen large open source projects use custom commands or tagging bots to trigger actions (like issue assignment and benchmark runs). I can figure it out.

We can start with cron. and add the manual trigger as we figure it out.

**Comment by abelsiqueira** [comment]
I prefer to focus on the PR part. The regression after things are merged is not so useful unless you're comparing between releases, IMO.
I've seen some projects with the triggering comment implemented. Actually, I think one of the JSO ones. I just haven't been paying enough attention to remember what they did.
I think you can run on "comment on PR" instead of `workflow_dispatch`.

**Comment by abelsiqueira** [comment]
The actions run on the main repo, so the permissions of the main apply. However, since we are admins of the main repo, when we issue `/benchmark`, it should use the right permissions. We still need to allow `write` in the `permissions` of `pull_request`, I believe (https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs).

**Comment by suvayu** [comment]
Just to let you know, I solved it! PR coming soon!
