### ISSUE TITLE
Data structures to JuMP Model

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#61]
Change the model formulation to include the following:

- [x] #107
- [x] #108
- [x] #135
- [x] #109
- [x] #110
- [x] #217
  - views with index arrays?
  - any other paradigm (ask @lsoucasse)? 
- [x] #123

Test cases:
See #88

**Comment by abelsiqueira** [comment]
Also add the Nordic test, please.

**Comment by clizbe** [comment]
I moved the test cases to the other epic #88. "Creating" the test cases makes more sense there. 
Of course you can make more issues for converting specific test cases, if necessary.

**Comment by abelsiqueira** [comment]
I think this can be closed.
