### ISSUE TITLE
Update citation.cff file

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#619]
### What and Why

We need to update the list of authors for the repo in the cff file.

Talk to @g-moralesespana before updating this file.

**Comment by clizbe** [comment]
Add Mathijs de Weerdt!

**Comment by clizbe** [comment]
Yeah this is a bit of a discussion of software vs research/publication.

**Comment by datejada** [comment]
After discussion, there are no changes in the CFF file for now.
