### ISSUE TITLE
Add a repo checklist to README.DEV

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#630]
### Description

We should have a checklist people can follow to make sure future repos are up to our standards.
Feel free to add to the list below:

**All Repos**
- Use BestieTemplate
  - Citation CFF included?
  - Add PR & Issue Templates
  - Formatter & Linter (defaults are for Julia)
- Zenodo DOI
  - See https://github.com/TulipaEnergy/TulipaPlots.jl/issues/26
- Protect the main branch
- Register package

**Tulipa Repos**
- Docs that point to TulipaEnergyModel (if a Tulipa repo)
  - Common stuff lives on TEM, package-specific lives in package
- Match the labels (Types, Zones) so we can label Issues on the Project board

**Comment by datejada** [comment]
@clizbe, do we still need this issue? I think we have it covered using BestieTemplate since it is now applied to all the TulipaX repositories.

**Comment by clizbe** [comment]
Yeah BestieTemplate covers most of it, but maybe we still need a Developer docs section about creating a new package in the project? I don't think Bestie protects the main branch, for instance. We don't need to repeat all the stuff like what's required to register a Julia package, but maybe a procedure to follow that includes "Start with BestieTemplate" and a few other things.

**Comment by clizbe** [comment]
😅 Of course!

**Comment by clizbe** [comment]
Looks like Bestie saves the day again with the Setting Up Your Package section!
https://juliabesties.github.io/BestieTemplate.jl/stable/10-full-guide/#Setting-up-your-package

I think that covers most of it. Maybe just protecting Main branch, but maybe we don't have to document that?

**Comment by abelsiqueira** [comment]
PRs adding branch protection to Besties docs are welcome
