### ISSUE TITLE
Use the input schema again

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#636]
### What and Why

The input schema stopped being used in #634 (except for some mandatory conversions). The validation should be reintroduced.

There are at least two options:
- Use it to validate while reading the CSVs. This means passing arguments to the TulipaIO functions to be used explicitly in the CSV reading. This is too specific, so it is not ideal.
- Validate in the TEM side, after the DB tables are created. It is not clear yet how to do it in a nice way.

**Comment by datejada** [comment]
Done in PR #737
