### ISSUE TITLE
Rename the variables and constraints dataframes in the model

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#642]
### What and Why

Rename constraint partitions to be closer to the constraint name itself (e.g., power or balance).
We are also updating the definition of `TulipaConstraint` to allow multiple `@constraint`s to be defined for the same `TulipaConstraint`, i.e, same indices. We do require that each `@constraint` use a full index set, i.e., no filtering of the rows of a constraint table.

### Related Issues

**variables**

- [ ] Rename variable table names to names in Miro - e.g. `var_storage_level_intra_rp` becomes `var_storage_rep_period`
- [ ] Rename variable key names and other places to reflect the table names - e.g., `variables[:storage_level_intra_rp]` becomes `variables[:storage_rep_period]`

**constraints**

- [x] #957
- [x] #958
- [x] Rename, split, create new constraints for each file:
  - [x] #961
    - [x] `assets_profile_times_capacity_out` should be duplicated and attached to corresponding tables
    - [ ] split `capacity_outgoing` into compact and simple and use for `max_output_...`
    - [x] Remove `acc..._inv..._lim...` expression
    - [x] Create new tables `max_output..._binary_part1` and `...part2` for outputs and for inputs (4 tables). Use a name that reflect using investment limit and accumulated investment, binary, etc.
  - [x] Rename, split, create new constraints for consumer.jl
  - [x] Rename, split, create new constraints for conversion.jl
  - [x] Rename, split, create new constraints for energy.jl
  - [x] #969
  - [x] Rename, split, create new constraints for hub.jl
  - [x] #964
    - [ ] Create constraint `limit_units_on`. Copy from `units_on` variable and update Miro
    - [ ] Create constraints `min_output_...` and `max_output_...` similar to `ramping_with_unit_commitment` (file ramp...jl). This requires two tables, since they don't have the same indices
    - [ ] Rename expression `units_on`, at least inside the file ramp...jl
    - [ ] Create a new table `max_ramp_with_unit_commitment` to attach `max_ramp_up_...` and `min_ramp_up...`
    - [ ] Create new table `max_ramp_without_unit_commitment` to attach related `max_ramp` constraints. Notice that `k = 1` will be an exception case, for now set to `0.0 == 0.0`.
    - [ ] `assets_profile_times_capacity_out` should be duplicated and attached to corresponding tables
  - [x] #966
  - [x] Rename, split, create new constraints for transport.jl

**Comment by datejada** [comment]
Part of discussion #688

**Comment by abelsiqueira** [comment]
Update: The names have been discussed and updated in the Miro board

**Comment by clizbe** [comment]
@abelsiqueira I have hunted for the fabled Miro board, but alas, I fear it is only legend...

**Comment by abelsiqueira** [comment]
I sent you an invitation. The links was sent on Teams. It can't be put on the issue because the link grants access to **anyone** to edit.

**Comment by clizbe** [comment]
Thanks! I remembered you sent the link but didn't think to check Teams. I have it bookmarked now.
