### ISSUE TITLE
Add DOCUMENTER_KEY to secrets

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#66]
### Summary

This key is used by the TagBot and can be used by CompatHelper. It allows them to make commits, pull requests, etc., using a user's SSH key.

### Basic Example

To generate use

```julia
pkg> activate --temp
pkg> add DocumenterTools
julia> using DocumenterTools
julia> DocumenterTools.genkeys(user="TulipaEnergy", repo="TulipaEnergyModel.jl")
```
Then follow the instructions.

### Drawbacks

None.

**Comment by abelsiqueira** [comment]
@clizbe, can you do this one?

**Comment by clizbe** [comment]
Done!
