### ISSUE TITLE
Rename `rep_periods_data.id` to `rep_periods_data.rep_period` for consistency

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#661]
### What and Why

We don't have `id` for anything else, instead we use the value of the thing as identifier, so it makes sense to change this to `rep_period`. It is also used as `rep_period` or `rp` in other places.

**Comment by datejada** [comment]
@abelsiqueira, if you are not working on this, I can take it.

**Comment by abelsiqueira** [comment]
Go ahead 👍
