### ISSUE TITLE
Use the original assets and flows profiles table

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#663]
### What and Why

Dealing with the whole pipeline, the `assets_rep_periods_profiles` will be the same as `assets_profiles`. I.e., the profiles have changed to be defined only on representative periods, but their name will be kept and so their link to assets and flows is the same.
With that in mind, we should change the expected name of the table to be `assets_profiles` (or create a variable somewhere to keep this info).

**Comment by datejada** [comment]
@abelsiqueira, what should we do with the `assets-timeframe-profiles` file? It seems that we can use one unique file with an extra column to identify if it is a representative period profile or a timeframe profile. Both types of profiles can be generated from TulipaClustering from the complete hourly data of the profiles.

What do you think?

**Comment by abelsiqueira** [comment]
I think it makes sense to keep separate, at least for now. They would all have empty or null `rep_period`, so it would be strange. But maybe it makes sense in the future to generalise.

**Comment by datejada** [comment]
Ok! It will look a little bit ugly seems it won't follow the current convention of names. But, I will propose a change in the PR and then you can give some feedback on the changes. Thanks!

**Comment by abelsiqueira** [comment]
I'm not sure I understand, let's see after the PR.

**Comment by datejada** [comment]
It was not that bad after all, but it has an 'if' statement when reading that can be generalised later if we use one file to define both types of profiles. The PR is ready for your review 😄
