### ISSUE TITLE
Apply BestieTemplate.jl

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#676]
### What and Why

The [BestieTemplate.jl](https://github.com/abelsiqueira/BestieTemplate.jl) was created using the best practices that we introduced in this package, so for many parts, this package is up-to-date in those practices.
However, since it was created, there were improvements in the BestieTemplate that we should apply here and the easier way to do it is by adopting the template.

The template was applied to [TulipaIO](https://github.com/TulipaEnergy/TulipaIO.jl) recently (in two parts, check the merged PRs). It was named COPIERTemplate.jl at the moment.

Some of the things:

- Link checker was removed from pre-commit and moved to a separate Linting with a different faster package (lychee)
- Dependabot was added (#444)
- An action checking for updates of the pre-commit versions was added
- It helps with this checklist (#630)
- Better solution for testing on the PR 
- Maybe [All Contributors](https://allcontributors.org)

If we do decide to apply it, we should wait until at least Monday, when the Registration of the rename will be done.

### Possible Drawbacks

There are different choices, such as the issue and PR templates are different, the formatting is slightly different, and the README.dev and CONTRIBUTING files moved to the docs.

It takes some time to apply it the first time, since you have to fix the conflicts (though I can help with that).

I am biased, since I'm lead on the project.

**Comment by clizbe** [comment]
Sounds good to me. Of course you're biased, but so far drinking your Kool-Aid has worked out well for us. :)

What do you mean by the README.dev and CONTRIBUTING files moved to the docs?
