### ISSUE TITLE
Fix readme.dev to our fork workflow

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#696]
### What and Why

Readme.dev currently has users clone their fork (thus making it origin).
Whereas we (or at least I) have my fork as myfork, and the parent repo as origin, as well as upstream.

For example from the pipeline repo:
![image](https://github.com/user-attachments/assets/cfcb1bfb-2411-4fcc-9c42-a8b20da9128b)

**************

Change docs to reflect the result of the discussion:
- Fetch from upstream = core repo
- Push to origin = own clone

This also matches BestieTemplate.jl - so once we use Bestie these docs will probably be redundant.

### Possible Drawbacks

~Not sure we're all working with this same flow?~

### Related Issues

- #695 
- #676

**Comment by abelsiqueira** [comment]
Maybe relates to #676

**Comment by gnawin** [comment]
@clizbe I have my fork named "fork", and the remote named "upstream", as this is easier for me. The naming seems to me is just a user choice. So, as you've shown, you can even have two names for the remote, didn't know that before...

**Comment by clizbe** [comment]
I think the difference is that you keep your personal remote fork (gnawin/TEM) up to date and fetch/pull from there. Whereas I fetch from the main remote repo (TulipaEnergy/TEM) and my fork is completely behind, but I push my branches there before making a PR. They're about the same, it just depends if you pull your updates from your own fork or the main repo. If you pull from your own fork you have to keep it up to date as well. 🤔

**Comment by clizbe** [comment]
Not sure what upstream is used for. XD

**Comment by gnawin** [comment]
> I think the difference is that you keep your personal remote fork (gnawin/TEM) up to date and fetch/pull from there. Whereas I fetch from the main remote repo (TulipaEnergy/TEM) and my fork is completely behind, but I push my branches there before making a PR. They're about the same, it just depends if you pull your updates from your own fork or the main repo. If you pull from your own fork you have to keep it up to date as well. 🤔
> 
> But I could be totally wrong - I think upstream is where your default fetch is from.

Yeah, it just depends on where you pull your updates from. In readme.dev, it says 
`git merge --ff-only origin/main`. In my case, I just changed my remote name to _upstream_ because I don't like `origin`, so my own workflow is `git merge --ff-only upstream/main` 😄 . So our workflows are the same, just with different names for the remote (meaning that my fork is also very much behind).

**Comment by abelsiqueira** [comment]
We discussed this yesterday in person. Solution is to remove "myfork" from docs and/or use #676.
