### ISSUE TITLE
How to get a column from DuckDB directly?

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#714]
### What and Why

So we don’t do `df -> df.column`

We tried this code, but sometimes it fails with r being missing.

```julia
r = DBInterface.execute(con, "SQL")
r.tbl.column
```

@suvayu Any ideas? Maybe it is an async issue

**Comment by suvayu** [comment]
You can't, you have to collect it to get the result; see duckdb/duckdb#11196.  Maybe `DBInterface.query(con, "<SQL>")` works without collect?

**Comment by clizbe** [comment]
@datejada Is this still an issue?

**Comment by datejada** [comment]
> @datejada Is this still an issue?

Nop, the answer is in Suvayu's comment https://github.com/TulipaEnergy/TulipaEnergyModel.jl/issues/714#issuecomment-2260709449. So, closing this issue.

Thanks for keeping an eye on the issues 😄
