### ISSUE TITLE
Add basic investment model (obj, upper bounds, conversion, cost efficiency), and create the needed parameters

### ISSUE THREAD

**Issue by gnawin** [TulipaEnergy/TulipaEnergyModel.jl#722]
- Add a year dimension to input files. Be careful to differentiate raw input files and generated files. E.g., add years to profile names, where you can use same name/profiles for different years, so you don't duplicate in files with profiles.
- For existing (single-year) assets, flow data files, add the year dimension also, give a default value, like "1".
- Assets, flow data files should be refactored such that you have a base data file, and other files with yearly data. This separation  is in the refactor process @abelsiqueira @datejada.

After discussion, we will split this issue/PR #741.

- [x] #748 
- [x] #758
- [x] #787
- [ ] #759
- [ ] Modify the rest of the model. If needed, split further.

**Comment by gnawin** [comment]
This one is blocked by #732

**Comment by datejada** [comment]
Closed in favor of https://github.com/TulipaEnergy/TulipaEnergyModel.jl/issues/783
