### ISSUE TITLE
Add information for diff of CSV files

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#753]
### What and Why

The following command shows diff between csv files:

```
git diff --word-diff-regex="[^[:space:],]+"
```

It can be added to the developer documentation.

**Comment by clizbe** [comment]
In which section? I guess for comparing input files?

**Comment by abelsiqueira** [comment]
Yes, that's good.

**Comment by clizbe** [comment]
How do you use csv files with this command?

**Comment by clizbe** [comment]
When I try to use it to compare assets-data and bad-assets-data I get this:
![Image](https://github.com/user-attachments/assets/92ab71f8-8b5a-4d00-b733-f9771db632c4)

**Comment by clizbe** [comment]
Nvm I figured it out. It needs the argument --no-index if it's outside a repo.
https://stackoverflow.com/questions/1721738/using-diff-or-anything-else-to-get-character-level-diff-between-text-files
