### ISSUE TITLE
Create multi-year test data

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#758]
@gnawin, this is to keep track of the Multi-year data discussion.

After #757, we have a proper new structure for data, but since things are moving fast, that might change before we finish this issue. Let's try to add this data separately, so it doesn't become part of the issue. So let's try to make a script that generates the data from some of the existing input - with something else external, if necessary.

- Is the Multi-year data generated from any of the other files?
- Is there external data that is being added (e.g., another profile)
- Can we create a high-level script/description of how to write the multi-year data?
  - E.g., "take the Tiny data, copy all rows from assets-data but change the year to 2050. Then ..."

**Comment by gnawin** [comment]
In general, I see 3 parts to complete the multi-year data.
- Create a minimum example of the data, e.g., from other inputs. This can be a tiny version of input for the tiny test case. Or simply use the tiny case and add different years to that. And we may want to change some parameters, e.g., `investable` to test some cases.
- Some data that is now elsewhere, which is the data about initial capacities. In the test case, we'll make up some data that mimics what we have in the other data based.
- Some parameters that we'll need for multi-year, but currently missing from the current struct. 

So to your questions

- Is the Multi-year data generated from any of the other files?
  Yes, now starting from Tiny.
- Is there external data that is being added (e.g., another profile)
  Yes, we need external data (initial capacity data) and more profiles.
- Can we create a high-level script/description of how to write the multi-year data?
  - E.g., "take the Tiny data, copy all rows from assets-data but change the year to 2050. Then ..."
  - Here's how I would write it:
    - Take the Tiny data, copy all rows from assets-data but change the year to 2050, so we have 2030 and 2050 data. 
    - Then add initial capacity data, which is currently elsewhere so we need to make up something.
    - Add the missing parameters, e.g., `technical lifetime`

**Comment by abelsiqueira** [comment]
Can you provide these things so I can generate the data so we can move ahead with the rebase for you to continue the rest of the model, or should I change the order and implement the changes without the multi-year data?

**Comment by abelsiqueira** [comment]
Let me clarify that I don't want to implement your model, just continue with the refactor of the huge PR adding the structures
