### ISSUE TITLE
Add policy questions to answer with the model to the docs

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#775]
### What and Why

Add a new subsection on the docs home page to include a general overview of the type of policy questions that TulipaEnergyModel can answer.

This is a recommendation of the stakeholders' monthly meeting.

### Possible Drawbacks

N.A.

### Related Issues

N.A.

**Comment by datejada** [comment]
@clizbe would you like to pick this one? I think you have a good overview and writing to make it appealing and informative 😄 if you have the time and fancy to do it, of course 😉

**Comment by clizbe** [comment]
Uhh maybe but I think I might need help knowing the actual analyses possible with current vs future features.
