### ISSUE TITLE
Publish the package!

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#82]
### Summary

We should publish the package ASAP so we can dibs the name.

### Basic Example

Do it, quick!

### Drawbacks

We might start seeing responses from the "community."
We have to start dealing with version releases.

**Comment by datejada** [comment]
Before publishing, let's check the following:

- [ ] We have the CITATION.cff file (issue #11)
- [ ] We add to the README file the citation to the preprint

**Comment by clizbe** [comment]
- [ ] Finish README #10

**Comment by datejada** [comment]
The package was published in #117
