### ISSUE TITLE
[BUG] - Italics in docs

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#847]
### Description

Once again we have a weird italics problem in the docs. It's in the Schemas section this time.
Can fix it using `

![image](https://github.com/user-attachments/assets/417a27c1-b556-43b0-941d-916875e52645)

### Reproduction steps

```bash
Look at the docs: How to Use > Input > Schemas
```

**Comment by abelsiqueira** [comment]
I think this is the place: https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/main/docs/src/how-to-use.md#schemasid-schemas
The code is reproduced below:

```julia
using Markdown, TulipaEnergyModel

Markdown.parse(
    join(["- **$filename**\n" *
        join(
            ["  - `$f: $t`" for (f, t) in schema],
            "\n",
        ) for (filename, schema) in TulipaEnergyModel.schema_per_table_name
    ] |> sort, "\n")
)
```

I think we have to replace the "_" in `filename` by "\_" (or "\\_") and that should fix it.
