### ISSUE TITLE
Update online codecov requirement to 98%

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#849]
### What and Why

Local codecov is 100%, but because of JuMP if-statements we have to jerry-rig the online coverage to reach 100%.
This is silly - let's remove the jerry-rigging and set the acceptable threshold to 98% (taking after JuMP).
Coverage tests will still break if new code in a PR has lower coverage than main.

### Possible Drawbacks

Slippery slope!

**Comment by clizbe** [comment]
@abelsiqueira <3

**Comment by datejada** [comment]
This is relevant post

**Comment by abelsiqueira** [comment]
We discussed in person the valid coverage ranges.
