### ISSUE TITLE
Update line-endings directions in README.dev

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#85]
### Summary

Part of the README references "TulipaBulb.jl" which has since been changed to "TulipaEnergyModel." This should be updated.

### Basic Example

![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/2b9a6a8e-9023-45a5-873a-20b6b611aff1)

### Drawbacks

None!

### Reference Issues

#41

**Comment by suvayu** [comment]
Hi, I think for this kind of obvious issues, it's okay to submit a PR directly. After all, the PR also has a similar template.

**Comment by abelsiqueira** [comment]
But also okay to open an issue if you're working on something else.

**Comment by suvayu** [comment]
It's a two line change. There's already too many notifications from this repo.
