### ISSUE TITLE
ESDL to CSV

### ISSUE THREAD

**Issue by lsoucasse** [TulipaEnergy/TulipaEnergyModel.jl#88]
Convert ESDL to GML + CSV and back
(Most likely a python script on another repository.)

- [ ] #89
- [x] #91
- [ ] Handle aggregated attributes
  - e.g. variable cost can be a sum of different costs
- [x] #102
  - (maybe part of #91?)

See also #63 for more info/discussion.

Test cases:
- [x] #100
- [x] #111
- [x] #101
- [ ] #112

**Comment by clizbe** [comment]
We need to reconsider this epic and how we're doing our data-handling and scenario building.
Need to talk to Suvayu about SpineToolbox and see what ESDL/EDR brings on top of data-sharing.

**Comment by clizbe** [comment]
Blocked until we figure out #237

**Comment by clizbe** [comment]
While two issues are still relevant, I'm closing this Epic as we're now using #289.
