### ISSUE TITLE
Update the issue templates

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#90]
### Summary

For internal use, the issue templates are too constraining.

### Basic Example

Epic is an example of issue that doesn't match what we want.

### Drawbacks

We don't want other people to be able to create epic issues (maybe that can be enforced?)

**Comment by sjvrijn** [comment]
Restricting access to certain issue templates does not seem to be supported.
The only thing I've found related to it is a [9-month old, unanswered question on StackOverflow](https://stackoverflow.com/questions/74715719/how-to-create-github-issue-template-that-is-only-visible-to-certain-team)

**Comment by sjvrijn** [comment]
For any other issues, do we simply re-enable blank issues?
If not, what do we want in an explicit 'other' template?
