### ISSUE TITLE
Instead of DF, use a TulipaIO table

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#909]
Like what is done for `dataframes[:flows]` in #896, using the strangle pattern.

Storage
- [ ] storage_level_intra_rp
- [ ] storage_level_inter_rp
- [ ] is_charging

Unit Commitment
- [x] #911

**Comment by gnawin** [comment]
Storage variables are blocked for now, because they need tables for storage constraints.

**Comment by abelsiqueira** [comment]
Done in #924
