### ISSUE TITLE
Associate parameters (from ESDL) with asset/flow attributes

### ISSUE THREAD

**Issue by lsoucasse** [TulipaEnergy/TulipaEnergyModel.jl#91]
Ensure compatibility between ESDL asset/flows attributes with the model formulation. 

The strategy is to play with the map editor to understand how parameters are assigned to flows/assets in ESDL. Then, compare with formulation and see if something has to be changed either on the ESDL side or on the model side.

**Comment by datejada** [comment]
This should be part of #89
