### ISSUE TITLE
Try using `@timeit to` on function calls, not on `begin ... end` blocks

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#934]
### Description

When an error happens inside the `begin ... end` block, the`@timeit` macro will hide the line where the error happened by just saying that the error happens at the macro line, and they listing `macro expansion` errors - which is unhelpful

**Comment by clizbe** [comment]
I'm just throwing all your Issues in "Now," but feel free to shift them later if they aren't urgent.

**Comment by abelsiqueira** [comment]
@gnawin
