### ISSUE TITLE
CSV to data structures

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#94]
Create the data structure that the model consumes.

- [x] #118
- [x] #103
- [x] #104
- [x] #105
- [x] #106
- [x] #261
- [x] #262
- [x] #263

**Comment by datejada** [comment]
waiting on https://github.com/TulipaEnergy/TulipaEnergyModel.jl/issues/110

**Comment by clizbe** [comment]
Blocked until figure out #237

**Comment by clizbe** [comment]
Done! Just need to figure out how to do it without CSVs now...
