### ISSUE TITLE
Change the Tulipa logo

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#99]
### Summary

The style of the current logo looks a bit dated to me.
We should make a new one.

I think we should choose a simple design that we can change the color of the tulip for different packages.
And MAYBE have the main package with Julia colors (although that will be ugly).

### Basic Example

I think these random examples from Google look more modern:
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/ab7737ff-8818-41f4-8e45-7242c77ab0de)
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/769df182-79fd-4a22-bbdf-cc8df58b0328)
![image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/11889283/a56412c6-5235-484b-ad48-418dd1bc0c63)

### Drawbacks

People might like the current style.
Developing the model is more important than the logo.

**Comment by clizbe** [comment]
@datejada had the awesome idea of crowd-sourcing this by making a **competition within the department.**

We could give them some guidelines and a timeframe and then judge the submissions and give them a De Sering card as the prize! (That prize is only €50, whereas hiring someone or giving hours would be waaay more expensive.)

I like this idea because it would advertise the model to the department, as well as hopefully create a bit of fun community. :)

Submissions can be anonymous through me - so anyone (including us) can submit, and people can make them themselves or use AI!

**Comment by suvayu** [comment]
> people can make them themselves or use AI!

I think we should disallow AI since the copyright status of AI generated works are unclear.

**Comment by clizbe** [comment]
The competition has started! Designs are due 30 Nov and we'll vote after that.
We didn't say anything about AI, so it's up to participants. If we choose an AI design I doubt we'll get famous enough that it ever matters.

**Comment by datejada** [comment]
We have a winner!

![Image](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/assets/12887482/ec40bc49-2892-491b-ae6d-32718a36ca2e)
